<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fedex.proto

namespace Carrier\Fedex\RequestedShipment;

use UnexpectedValueException;

/**
 * 包装方式枚举
 *
 * Protobuf type <code>fedex.RequestedShipment.PackagingType</code>
 */
class PackagingType
{
    /**
     * Generated from protobuf enum <code>YOUR_PACKAGING = 0;</code>
     */
    const YOUR_PACKAGING = 0;
    /**
     * Generated from protobuf enum <code>FEDEX_ENVELOPE = 1;</code>
     */
    const FEDEX_ENVELOPE = 1;
    /**
     * Generated from protobuf enum <code>FEDEX_BOX = 2;</code>
     */
    const FEDEX_BOX = 2;
    /**
     * Generated from protobuf enum <code>FEDEX_SMALL_BOX = 3;</code>
     */
    const FEDEX_SMALL_BOX = 3;
    /**
     * Generated from protobuf enum <code>FEDEX_MEDIUM_BOX = 4;</code>
     */
    const FEDEX_MEDIUM_BOX = 4;
    /**
     * Generated from protobuf enum <code>FEDEX_LARGE_BOX = 5;</code>
     */
    const FEDEX_LARGE_BOX = 5;
    /**
     * Generated from protobuf enum <code>FEDEX_EXTRA_LARGE_BOX = 6;</code>
     */
    const FEDEX_EXTRA_LARGE_BOX = 6;
    /**
     * Generated from protobuf enum <code>FEDEX_10KG_BOX = 7;</code>
     */
    const FEDEX_10KG_BOX = 7;
    /**
     * Generated from protobuf enum <code>FEDEX_25KG_BOX = 8;</code>
     */
    const FEDEX_25KG_BOX = 8;
    /**
     * Generated from protobuf enum <code>FEDEX_PAK = 9;</code>
     */
    const FEDEX_PAK = 9;
    /**
     * Generated from protobuf enum <code>FEDEX_TUBE = 10;</code>
     */
    const FEDEX_TUBE = 10;

    private static $valueToName = [
        self::YOUR_PACKAGING => 'YOUR_PACKAGING',
        self::FEDEX_ENVELOPE => 'FEDEX_ENVELOPE',
        self::FEDEX_BOX => 'FEDEX_BOX',
        self::FEDEX_SMALL_BOX => 'FEDEX_SMALL_BOX',
        self::FEDEX_MEDIUM_BOX => 'FEDEX_MEDIUM_BOX',
        self::FEDEX_LARGE_BOX => 'FEDEX_LARGE_BOX',
        self::FEDEX_EXTRA_LARGE_BOX => 'FEDEX_EXTRA_LARGE_BOX',
        self::FEDEX_10KG_BOX => 'FEDEX_10KG_BOX',
        self::FEDEX_25KG_BOX => 'FEDEX_25KG_BOX',
        self::FEDEX_PAK => 'FEDEX_PAK',
        self::FEDEX_TUBE => 'FEDEX_TUBE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(PackagingType::class, \Carrier\Fedex\RequestedShipment_PackagingType::class);

