<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ups.proto

namespace Carrier\Ups;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ups.AddressValidateResponse</code>
 */
class AddressValidateResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool ok = 1;</code>
     */
    protected $ok = false;
    /**
     * Generated from protobuf field <code>repeated string suggested_address = 2;</code>
     */
    private $suggested_address;
    /**
     * Generated from protobuf field <code>bool isResidential = 3;</code>
     */
    protected $isResidential = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $ok
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $suggested_address
     *     @type bool $isResidential
     * }
     */
    public function __construct($data = NULL) {
        \Carrier\Ups\Ups::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool ok = 1;</code>
     * @return bool
     */
    public function getOk()
    {
        return $this->ok;
    }

    /**
     * Generated from protobuf field <code>bool ok = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setOk($var)
    {
        GPBUtil::checkBool($var);
        $this->ok = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string suggested_address = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSuggestedAddress()
    {
        return $this->suggested_address;
    }

    /**
     * Generated from protobuf field <code>repeated string suggested_address = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSuggestedAddress($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->suggested_address = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isResidential = 3;</code>
     * @return bool
     */
    public function getIsResidential()
    {
        return $this->isResidential;
    }

    /**
     * Generated from protobuf field <code>bool isResidential = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsResidential($var)
    {
        GPBUtil::checkBool($var);
        $this->isResidential = $var;

        return $this;
    }

}

