<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ups.proto

namespace Carrier\Ups;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ups.Charge</code>
 */
class Charge extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string CurrencyCode = 1;</code>
     */
    protected $CurrencyCode = '';
    /**
     * Generated from protobuf field <code>double MonetaryValue = 2;</code>
     */
    protected $MonetaryValue = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $CurrencyCode
     *     @type float $MonetaryValue
     * }
     */
    public function __construct($data = NULL) {
        \Carrier\Ups\Ups::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string CurrencyCode = 1;</code>
     * @return string
     */
    public function getCurrencyCode()
    {
        return $this->CurrencyCode;
    }

    /**
     * Generated from protobuf field <code>string CurrencyCode = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCurrencyCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->CurrencyCode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double MonetaryValue = 2;</code>
     * @return float
     */
    public function getMonetaryValue()
    {
        return $this->MonetaryValue;
    }

    /**
     * Generated from protobuf field <code>double MonetaryValue = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setMonetaryValue($var)
    {
        GPBUtil::checkDouble($var);
        $this->MonetaryValue = $var;

        return $this;
    }

}

