<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ups.proto

namespace Carrier\Ups;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ups.CreateLabelResponse</code>
 */
class CreateLabelResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string label = 1;</code>
     */
    protected $label = '';
    /**
     * Generated from protobuf field <code>string tracking_number = 2;</code>
     */
    protected $tracking_number = '';
    /**
     * Generated from protobuf field <code>double total_charge = 3;</code>
     */
    protected $total_charge = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $label
     *     @type string $tracking_number
     *     @type float $total_charge
     * }
     */
    public function __construct($data = NULL) {
        \Carrier\Ups\Ups::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string label = 1;</code>
     * @return string
     */
    public function getLabel()
    {
        return $this->label;
    }

    /**
     * Generated from protobuf field <code>string label = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setLabel($var)
    {
        GPBUtil::checkString($var, True);
        $this->label = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string tracking_number = 2;</code>
     * @return string
     */
    public function getTrackingNumber()
    {
        return $this->tracking_number;
    }

    /**
     * Generated from protobuf field <code>string tracking_number = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTrackingNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->tracking_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double total_charge = 3;</code>
     * @return float
     */
    public function getTotalCharge()
    {
        return $this->total_charge;
    }

    /**
     * Generated from protobuf field <code>double total_charge = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setTotalCharge($var)
    {
        GPBUtil::checkDouble($var);
        $this->total_charge = $var;

        return $this;
    }

}

