<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ups.proto

namespace Carrier\Ups;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *尺寸
 *
 * Generated from protobuf message <code>ups.Dimensions</code>
 */
class Dimensions extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>double length = 1;</code>
     */
    protected $length = 0.0;
    /**
     * Generated from protobuf field <code>double width = 2;</code>
     */
    protected $width = 0.0;
    /**
     * Generated from protobuf field <code>double height = 3;</code>
     */
    protected $height = 0.0;
    /**
     * Generated from protobuf field <code>.ups.Unit unit = 4;</code>
     */
    protected $unit = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $length
     *     @type float $width
     *     @type float $height
     *     @type int $unit
     * }
     */
    public function __construct($data = NULL) {
        \Carrier\Ups\Ups::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>double length = 1;</code>
     * @return float
     */
    public function getLength()
    {
        return $this->length;
    }

    /**
     * Generated from protobuf field <code>double length = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setLength($var)
    {
        GPBUtil::checkDouble($var);
        $this->length = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double width = 2;</code>
     * @return float
     */
    public function getWidth()
    {
        return $this->width;
    }

    /**
     * Generated from protobuf field <code>double width = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setWidth($var)
    {
        GPBUtil::checkDouble($var);
        $this->width = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double height = 3;</code>
     * @return float
     */
    public function getHeight()
    {
        return $this->height;
    }

    /**
     * Generated from protobuf field <code>double height = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setHeight($var)
    {
        GPBUtil::checkDouble($var);
        $this->height = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ups.Unit unit = 4;</code>
     * @return int
     */
    public function getUnit()
    {
        return $this->unit;
    }

    /**
     * Generated from protobuf field <code>.ups.Unit unit = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setUnit($var)
    {
        GPBUtil::checkEnum($var, \Carrier\Ups\Unit::class);
        $this->unit = $var;

        return $this;
    }

}

