<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ups.proto

namespace Carrier\Ups;

use UnexpectedValueException;

/**
 * Protobuf type <code>ups.PackageType</code>
 */
class PackageType
{
    /**
     * Generated from protobuf enum <code>LETTER = 0;</code>
     */
    const LETTER = 0;
    /**
     * Generated from protobuf enum <code>PACKAGE = 1;</code>
     */
    const PACKAGE = 1;

    private static $valueToName = [
        self::LETTER => 'LETTER',
        self::PACKAGE => 'PACKAGE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

