<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ups.proto

namespace Carrier\Ups;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *支付信息
 *
 * Generated from protobuf message <code>ups.Payment</code>
 */
class Payment extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string account_number = 1;</code>
     */
    protected $account_number = '';
    /**
     * Generated from protobuf field <code>.ups.Payment.Type payment_type = 2;</code>
     */
    protected $payment_type = 0;
    /**
     * Generated from protobuf field <code>.ups.Address address = 3;</code>
     */
    protected $address = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $account_number
     *     @type int $payment_type
     *     @type \Carrier\Ups\Address $address
     * }
     */
    public function __construct($data = NULL) {
        \Carrier\Ups\Ups::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string account_number = 1;</code>
     * @return string
     */
    public function getAccountNumber()
    {
        return $this->account_number;
    }

    /**
     * Generated from protobuf field <code>string account_number = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAccountNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->account_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ups.Payment.Type payment_type = 2;</code>
     * @return int
     */
    public function getPaymentType()
    {
        return $this->payment_type;
    }

    /**
     * Generated from protobuf field <code>.ups.Payment.Type payment_type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPaymentType($var)
    {
        GPBUtil::checkEnum($var, \Carrier\Ups\Payment\Type::class);
        $this->payment_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ups.Address address = 3;</code>
     * @return \Carrier\Ups\Address|null
     */
    public function getAddress()
    {
        return $this->address;
    }

    public function hasAddress()
    {
        return isset($this->address);
    }

    public function clearAddress()
    {
        unset($this->address);
    }

    /**
     * Generated from protobuf field <code>.ups.Address address = 3;</code>
     * @param \Carrier\Ups\Address $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkMessage($var, \Carrier\Ups\Address::class);
        $this->address = $var;

        return $this;
    }

}

