<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ups.proto

namespace Carrier\Ups;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ups.RateRequest</code>
 */
class RateRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.ups.Auth authorization = 1;</code>
     */
    protected $authorization = null;
    /**
     * Generated from protobuf field <code>.ups.Location shipper = 2;</code>
     */
    protected $shipper = null;
    /**
     * Generated from protobuf field <code>.ups.Location ship_from = 3;</code>
     */
    protected $ship_from = null;
    /**
     * Generated from protobuf field <code>.ups.Location ship_to = 4;</code>
     */
    protected $ship_to = null;
    /**
     * Generated from protobuf field <code>.ups.ServiceType service = 5;</code>
     */
    protected $service = 0;
    /**
     * Generated from protobuf field <code>.ups.Package package = 6;</code>
     */
    protected $package = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Carrier\Ups\Auth $authorization
     *     @type \Carrier\Ups\Location $shipper
     *     @type \Carrier\Ups\Location $ship_from
     *     @type \Carrier\Ups\Location $ship_to
     *     @type int $service
     *     @type \Carrier\Ups\Package $package
     * }
     */
    public function __construct($data = NULL) {
        \Carrier\Ups\Ups::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.ups.Auth authorization = 1;</code>
     * @return \Carrier\Ups\Auth|null
     */
    public function getAuthorization()
    {
        return $this->authorization;
    }

    public function hasAuthorization()
    {
        return isset($this->authorization);
    }

    public function clearAuthorization()
    {
        unset($this->authorization);
    }

    /**
     * Generated from protobuf field <code>.ups.Auth authorization = 1;</code>
     * @param \Carrier\Ups\Auth $var
     * @return $this
     */
    public function setAuthorization($var)
    {
        GPBUtil::checkMessage($var, \Carrier\Ups\Auth::class);
        $this->authorization = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ups.Location shipper = 2;</code>
     * @return \Carrier\Ups\Location|null
     */
    public function getShipper()
    {
        return $this->shipper;
    }

    public function hasShipper()
    {
        return isset($this->shipper);
    }

    public function clearShipper()
    {
        unset($this->shipper);
    }

    /**
     * Generated from protobuf field <code>.ups.Location shipper = 2;</code>
     * @param \Carrier\Ups\Location $var
     * @return $this
     */
    public function setShipper($var)
    {
        GPBUtil::checkMessage($var, \Carrier\Ups\Location::class);
        $this->shipper = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ups.Location ship_from = 3;</code>
     * @return \Carrier\Ups\Location|null
     */
    public function getShipFrom()
    {
        return $this->ship_from;
    }

    public function hasShipFrom()
    {
        return isset($this->ship_from);
    }

    public function clearShipFrom()
    {
        unset($this->ship_from);
    }

    /**
     * Generated from protobuf field <code>.ups.Location ship_from = 3;</code>
     * @param \Carrier\Ups\Location $var
     * @return $this
     */
    public function setShipFrom($var)
    {
        GPBUtil::checkMessage($var, \Carrier\Ups\Location::class);
        $this->ship_from = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ups.Location ship_to = 4;</code>
     * @return \Carrier\Ups\Location|null
     */
    public function getShipTo()
    {
        return $this->ship_to;
    }

    public function hasShipTo()
    {
        return isset($this->ship_to);
    }

    public function clearShipTo()
    {
        unset($this->ship_to);
    }

    /**
     * Generated from protobuf field <code>.ups.Location ship_to = 4;</code>
     * @param \Carrier\Ups\Location $var
     * @return $this
     */
    public function setShipTo($var)
    {
        GPBUtil::checkMessage($var, \Carrier\Ups\Location::class);
        $this->ship_to = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ups.ServiceType service = 5;</code>
     * @return int
     */
    public function getService()
    {
        return $this->service;
    }

    /**
     * Generated from protobuf field <code>.ups.ServiceType service = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setService($var)
    {
        GPBUtil::checkEnum($var, \Carrier\Ups\ServiceType::class);
        $this->service = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ups.Package package = 6;</code>
     * @return \Carrier\Ups\Package|null
     */
    public function getPackage()
    {
        return $this->package;
    }

    public function hasPackage()
    {
        return isset($this->package);
    }

    public function clearPackage()
    {
        unset($this->package);
    }

    /**
     * Generated from protobuf field <code>.ups.Package package = 6;</code>
     * @param \Carrier\Ups\Package $var
     * @return $this
     */
    public function setPackage($var)
    {
        GPBUtil::checkMessage($var, \Carrier\Ups\Package::class);
        $this->package = $var;

        return $this;
    }

}

