<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ups.proto

namespace Carrier\Ups;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ups.RateResponse</code>
 */
class RateResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>double billWeight = 1;</code>
     */
    protected $billWeight = 0.0;
    /**
     * Generated from protobuf field <code>double transportationCharge = 2;</code>
     */
    protected $transportationCharge = 0.0;
    /**
     * Generated from protobuf field <code>double baseServiceCharge = 3;</code>
     */
    protected $baseServiceCharge = 0.0;
    /**
     * Generated from protobuf field <code>double serviceOptionsCharge = 4;</code>
     */
    protected $serviceOptionsCharge = 0.0;
    /**
     * Generated from protobuf field <code>double totalCharge = 5;</code>
     */
    protected $totalCharge = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $billWeight
     *     @type float $transportationCharge
     *     @type float $baseServiceCharge
     *     @type float $serviceOptionsCharge
     *     @type float $totalCharge
     * }
     */
    public function __construct($data = NULL) {
        \Carrier\Ups\Ups::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>double billWeight = 1;</code>
     * @return float
     */
    public function getBillWeight()
    {
        return $this->billWeight;
    }

    /**
     * Generated from protobuf field <code>double billWeight = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setBillWeight($var)
    {
        GPBUtil::checkDouble($var);
        $this->billWeight = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double transportationCharge = 2;</code>
     * @return float
     */
    public function getTransportationCharge()
    {
        return $this->transportationCharge;
    }

    /**
     * Generated from protobuf field <code>double transportationCharge = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setTransportationCharge($var)
    {
        GPBUtil::checkDouble($var);
        $this->transportationCharge = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double baseServiceCharge = 3;</code>
     * @return float
     */
    public function getBaseServiceCharge()
    {
        return $this->baseServiceCharge;
    }

    /**
     * Generated from protobuf field <code>double baseServiceCharge = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setBaseServiceCharge($var)
    {
        GPBUtil::checkDouble($var);
        $this->baseServiceCharge = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double serviceOptionsCharge = 4;</code>
     * @return float
     */
    public function getServiceOptionsCharge()
    {
        return $this->serviceOptionsCharge;
    }

    /**
     * Generated from protobuf field <code>double serviceOptionsCharge = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setServiceOptionsCharge($var)
    {
        GPBUtil::checkDouble($var);
        $this->serviceOptionsCharge = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double totalCharge = 5;</code>
     * @return float
     */
    public function getTotalCharge()
    {
        return $this->totalCharge;
    }

    /**
     * Generated from protobuf field <code>double totalCharge = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setTotalCharge($var)
    {
        GPBUtil::checkDouble($var);
        $this->totalCharge = $var;

        return $this;
    }

}

