<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ups.proto

namespace Carrier\Ups;

/**
 * Protobuf type <code>ups.Service</code>
 */
interface ServiceInterface
{
    /**
     * Method <code>createLabel</code>
     *
     * @param \Carrier\Ups\CreateLabelRequest $request
     * @return \Carrier\Ups\CreateLabelResponse
     */
    public function createLabel(\Carrier\Ups\CreateLabelRequest $request);

    /**
     * Method <code>track</code>
     *
     * @param \Carrier\Ups\TrackRequest $request
     * @return \Carrier\Ups\TrackResponse
     */
    public function track(\Carrier\Ups\TrackRequest $request);

    /**
     * Method <code>rate</code>
     *
     * @param \Carrier\Ups\RateRequest $request
     * @return \Carrier\Ups\RateResponse
     */
    public function rate(\Carrier\Ups\RateRequest $request);

    /**
     * Method <code>addressValidate</code>
     *
     * @param \Carrier\Ups\AddressValidateRequest $request
     * @return \Carrier\Ups\AddressValidateResponse
     */
    public function addressValidate(\Carrier\Ups\AddressValidateRequest $request);

}

