<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ups.proto

namespace Carrier\Ups;

use UnexpectedValueException;

/**
 * Protobuf type <code>ups.ServiceType</code>
 */
class ServiceType
{
    /**
     * Generated from protobuf enum <code>NEXT_DAY_AIR = 0;</code>
     */
    const NEXT_DAY_AIR = 0;
    /**
     * Generated from protobuf enum <code>SECOND_DAY = 1;</code>
     */
    const SECOND_DAY = 1;
    /**
     * Generated from protobuf enum <code>GROUND = 2;</code>
     */
    const GROUND = 2;
    /**
     * Generated from protobuf enum <code>WORLDWIDE_EXPRESS = 3;</code>
     */
    const WORLDWIDE_EXPRESS = 3;
    /**
     * Generated from protobuf enum <code>WORLDWIDE_EXPEDITED = 4;</code>
     */
    const WORLDWIDE_EXPEDITED = 4;
    /**
     * Generated from protobuf enum <code>STANDARD = 5;</code>
     */
    const STANDARD = 5;
    /**
     * Generated from protobuf enum <code>DAY_3_SELECT = 6;</code>
     */
    const DAY_3_SELECT = 6;
    /**
     * Generated from protobuf enum <code>NEXT_DAY_AIR_SAVER = 7;</code>
     */
    const NEXT_DAY_AIR_SAVER = 7;
    /**
     * Generated from protobuf enum <code>NEXT_DAY_AIR_EARLY = 8;</code>
     */
    const NEXT_DAY_AIR_EARLY = 8;
    /**
     * Generated from protobuf enum <code>WORLDWIDE_EXPRESS_PLUS = 9;</code>
     */
    const WORLDWIDE_EXPRESS_PLUS = 9;
    /**
     * Generated from protobuf enum <code>SECOND_DAY_AIR_AM = 10;</code>
     */
    const SECOND_DAY_AIR_AM = 10;
    /**
     * Generated from protobuf enum <code>SAVER = 11;</code>
     */
    const SAVER = 11;
    /**
     * Generated from protobuf enum <code>SURE_POST_LESS_THAN_1LB = 12;</code>
     */
    const SURE_POST_LESS_THAN_1LB = 12;
    /**
     * Generated from protobuf enum <code>SURE_POST_1LB_OR_GREATER = 13;</code>
     */
    const SURE_POST_1LB_OR_GREATER = 13;
    /**
     * Generated from protobuf enum <code>SURE_POST_BPM = 14;</code>
     */
    const SURE_POST_BPM = 14;
    /**
     * Generated from protobuf enum <code>SURE_POST_MEDIA = 15;</code>
     */
    const SURE_POST_MEDIA = 15;
    /**
     * Generated from protobuf enum <code>FIRST_CLASS_MAIL = 16;</code>
     */
    const FIRST_CLASS_MAIL = 16;
    /**
     * Generated from protobuf enum <code>PRIORITY_MAIL = 17;</code>
     */
    const PRIORITY_MAIL = 17;
    /**
     * Generated from protobuf enum <code>EXPEDITED_MAIL_INNOVATION = 18;</code>
     */
    const EXPEDITED_MAIL_INNOVATION = 18;

    private static $valueToName = [
        self::NEXT_DAY_AIR => 'NEXT_DAY_AIR',
        self::SECOND_DAY => 'SECOND_DAY',
        self::GROUND => 'GROUND',
        self::WORLDWIDE_EXPRESS => 'WORLDWIDE_EXPRESS',
        self::WORLDWIDE_EXPEDITED => 'WORLDWIDE_EXPEDITED',
        self::STANDARD => 'STANDARD',
        self::DAY_3_SELECT => 'DAY_3_SELECT',
        self::NEXT_DAY_AIR_SAVER => 'NEXT_DAY_AIR_SAVER',
        self::NEXT_DAY_AIR_EARLY => 'NEXT_DAY_AIR_EARLY',
        self::WORLDWIDE_EXPRESS_PLUS => 'WORLDWIDE_EXPRESS_PLUS',
        self::SECOND_DAY_AIR_AM => 'SECOND_DAY_AIR_AM',
        self::SAVER => 'SAVER',
        self::SURE_POST_LESS_THAN_1LB => 'SURE_POST_LESS_THAN_1LB',
        self::SURE_POST_1LB_OR_GREATER => 'SURE_POST_1LB_OR_GREATER',
        self::SURE_POST_BPM => 'SURE_POST_BPM',
        self::SURE_POST_MEDIA => 'SURE_POST_MEDIA',
        self::FIRST_CLASS_MAIL => 'FIRST_CLASS_MAIL',
        self::PRIORITY_MAIL => 'PRIORITY_MAIL',
        self::EXPEDITED_MAIL_INNOVATION => 'EXPEDITED_MAIL_INNOVATION',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

