<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ups.proto

namespace Carrier\Ups;

if (false) {
    /**
     * This class is deprecated. Use Carrier\Ups\Shipment\Service instead.
     * @deprecated
     */
    class Shipment_Service {}
}
class_exists(Shipment\Service::class);
@trigger_error('Carrier\Ups\Shipment_Service is deprecated and will be removed in the next major release. Use Carrier\Ups\Shipment\Service instead', E_USER_DEPRECATED);

