<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ups.proto

namespace Carrier\Ups;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ups.Shipment</code>
 */
class Shipment extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.ups.Location shipper = 1;</code>
     */
    protected $shipper = null;
    /**
     * Generated from protobuf field <code>.ups.Location ship_from = 2;</code>
     */
    protected $ship_from = null;
    /**
     * Generated from protobuf field <code>.ups.Location ship_to = 3;</code>
     */
    protected $ship_to = null;
    /**
     * Generated from protobuf field <code>.ups.Payment payment = 4;</code>
     */
    protected $payment = null;
    /**
     * Generated from protobuf field <code>.ups.Shipment.Service service = 6;</code>
     */
    protected $service = 0;
    /**
     * Generated from protobuf field <code>.ups.Package package = 7;</code>
     */
    protected $package = null;
    /**
     * Generated from protobuf field <code>.ups.Shipment.LabelFormat label_format = 8;</code>
     */
    protected $label_format = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Carrier\Ups\Location $shipper
     *     @type \Carrier\Ups\Location $ship_from
     *     @type \Carrier\Ups\Location $ship_to
     *     @type \Carrier\Ups\Payment $payment
     *     @type int $service
     *     @type \Carrier\Ups\Package $package
     *     @type int $label_format
     * }
     */
    public function __construct($data = NULL) {
        \Carrier\Ups\Ups::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.ups.Location shipper = 1;</code>
     * @return \Carrier\Ups\Location|null
     */
    public function getShipper()
    {
        return $this->shipper;
    }

    public function hasShipper()
    {
        return isset($this->shipper);
    }

    public function clearShipper()
    {
        unset($this->shipper);
    }

    /**
     * Generated from protobuf field <code>.ups.Location shipper = 1;</code>
     * @param \Carrier\Ups\Location $var
     * @return $this
     */
    public function setShipper($var)
    {
        GPBUtil::checkMessage($var, \Carrier\Ups\Location::class);
        $this->shipper = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ups.Location ship_from = 2;</code>
     * @return \Carrier\Ups\Location|null
     */
    public function getShipFrom()
    {
        return $this->ship_from;
    }

    public function hasShipFrom()
    {
        return isset($this->ship_from);
    }

    public function clearShipFrom()
    {
        unset($this->ship_from);
    }

    /**
     * Generated from protobuf field <code>.ups.Location ship_from = 2;</code>
     * @param \Carrier\Ups\Location $var
     * @return $this
     */
    public function setShipFrom($var)
    {
        GPBUtil::checkMessage($var, \Carrier\Ups\Location::class);
        $this->ship_from = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ups.Location ship_to = 3;</code>
     * @return \Carrier\Ups\Location|null
     */
    public function getShipTo()
    {
        return $this->ship_to;
    }

    public function hasShipTo()
    {
        return isset($this->ship_to);
    }

    public function clearShipTo()
    {
        unset($this->ship_to);
    }

    /**
     * Generated from protobuf field <code>.ups.Location ship_to = 3;</code>
     * @param \Carrier\Ups\Location $var
     * @return $this
     */
    public function setShipTo($var)
    {
        GPBUtil::checkMessage($var, \Carrier\Ups\Location::class);
        $this->ship_to = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ups.Payment payment = 4;</code>
     * @return \Carrier\Ups\Payment|null
     */
    public function getPayment()
    {
        return $this->payment;
    }

    public function hasPayment()
    {
        return isset($this->payment);
    }

    public function clearPayment()
    {
        unset($this->payment);
    }

    /**
     * Generated from protobuf field <code>.ups.Payment payment = 4;</code>
     * @param \Carrier\Ups\Payment $var
     * @return $this
     */
    public function setPayment($var)
    {
        GPBUtil::checkMessage($var, \Carrier\Ups\Payment::class);
        $this->payment = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ups.Shipment.Service service = 6;</code>
     * @return int
     */
    public function getService()
    {
        return $this->service;
    }

    /**
     * Generated from protobuf field <code>.ups.Shipment.Service service = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setService($var)
    {
        GPBUtil::checkEnum($var, \Carrier\Ups\Shipment\Service::class);
        $this->service = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ups.Package package = 7;</code>
     * @return \Carrier\Ups\Package|null
     */
    public function getPackage()
    {
        return $this->package;
    }

    public function hasPackage()
    {
        return isset($this->package);
    }

    public function clearPackage()
    {
        unset($this->package);
    }

    /**
     * Generated from protobuf field <code>.ups.Package package = 7;</code>
     * @param \Carrier\Ups\Package $var
     * @return $this
     */
    public function setPackage($var)
    {
        GPBUtil::checkMessage($var, \Carrier\Ups\Package::class);
        $this->package = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ups.Shipment.LabelFormat label_format = 8;</code>
     * @return int
     */
    public function getLabelFormat()
    {
        return $this->label_format;
    }

    /**
     * Generated from protobuf field <code>.ups.Shipment.LabelFormat label_format = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setLabelFormat($var)
    {
        GPBUtil::checkEnum($var, \Carrier\Ups\Shipment\LabelFormat::class);
        $this->label_format = $var;

        return $this;
    }

}

