<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ups.proto

namespace Carrier\Ups;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pb.TrackActivity</code>
 */
class TrackActivity extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string code = 1;</code>
     */
    protected $code = '';
    /**
     * Generated from protobuf field <code>string description = 2;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>string signed_for_by_name = 3;</code>
     */
    protected $signed_for_by_name = '';
    /**
     * Generated from protobuf field <code>string status_type = 4;</code>
     */
    protected $status_type = '';
    /**
     * Generated from protobuf field <code>string status_code = 5;</code>
     */
    protected $status_code = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $code
     *     @type string $description
     *     @type string $signed_for_by_name
     *     @type string $status_type
     *     @type string $status_code
     * }
     */
    public function __construct($data = NULL) {
        \Carrier\Ups\Ups::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string code = 1;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Generated from protobuf field <code>string code = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 2;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string signed_for_by_name = 3;</code>
     * @return string
     */
    public function getSignedForByName()
    {
        return $this->signed_for_by_name;
    }

    /**
     * Generated from protobuf field <code>string signed_for_by_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSignedForByName($var)
    {
        GPBUtil::checkString($var, True);
        $this->signed_for_by_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string status_type = 4;</code>
     * @return string
     */
    public function getStatusType()
    {
        return $this->status_type;
    }

    /**
     * Generated from protobuf field <code>string status_type = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setStatusType($var)
    {
        GPBUtil::checkString($var, True);
        $this->status_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string status_code = 5;</code>
     * @return string
     */
    public function getStatusCode()
    {
        return $this->status_code;
    }

    /**
     * Generated from protobuf field <code>string status_code = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setStatusCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->status_code = $var;

        return $this;
    }

}

