<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ups.proto

namespace Carrier\Ups;

use UnexpectedValueException;

/**
 * Protobuf type <code>ups.Unit</code>
 */
class Unit
{
    /**
     * Generated from protobuf enum <code>LBS = 0;</code>
     */
    const LBS = 0;
    /**
     * Generated from protobuf enum <code>OZS = 1;</code>
     */
    const OZS = 1;
    /**
     * Generated from protobuf enum <code>IN = 2;</code>
     */
    const IN = 2;
    /**
     * Generated from protobuf enum <code>CM = 3;</code>
     */
    const CM = 3;

    private static $valueToName = [
        self::LBS => 'LBS',
        self::OZS => 'OZS',
        self::IN => 'IN',
        self::CM => 'CM',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

