<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fedex.proto

namespace Carrier\Fedex\Weight;

use UnexpectedValueException;

/**
 * 单位
 *
 * Protobuf type <code>fedex.Weight.Unit</code>
 */
class Unit
{
    /**
     * Generated from protobuf enum <code>KG = 0;</code>
     */
    const KG = 0;
    /**
     * Generated from protobuf enum <code>LB = 1;</code>
     */
    const LB = 1;

    private static $valueToName = [
        self::KG => 'KG',
        self::LB => 'LB',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Unit::class, \Carrier\Fedex\Weight_Unit::class);

