<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rocket.proto

namespace Carrier\Rocket\RateParams;

use UnexpectedValueException;

/**
 * 长度单位枚举
 *
 * Protobuf type <code>rocket.RateParams.LengthUnit</code>
 */
class LengthUnit
{
    /**
     * Generated from protobuf enum <code>IN = 0;</code>
     */
    const IN = 0;
    /**
     * Generated from protobuf enum <code>CM = 1;</code>
     */
    const CM = 1;

    private static $valueToName = [
        self::IN => 'IN',
        self::CM => 'CM',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(LengthUnit::class, \Carrier\Rocket\RateParams_LengthUnit::class);

