<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rocket.proto

namespace Carrier\Rocket\RateParams;

use UnexpectedValueException;

/**
 * 重量单位枚举
 *
 * Protobuf type <code>rocket.RateParams.WeightUnit</code>
 */
class WeightUnit
{
    /**
     * Generated from protobuf enum <code>LBS = 0;</code>
     */
    const LBS = 0;

    private static $valueToName = [
        self::LBS => 'LBS',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(WeightUnit::class, \Carrier\Rocket\RateParams_WeightUnit::class);

