<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fedex.proto

namespace Carrier\Fedex;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 地址
 *
 * Generated from protobuf message <code>fedex.Address</code>
 */
class Address extends \Google\Protobuf\Internal\Message
{
    /**
     * 街道
     *
     * Generated from protobuf field <code>repeated string street_lines = 1;</code>
     */
    private $street_lines;
    /**
     * 市
     *
     * Generated from protobuf field <code>string city = 2;</code>
     */
    protected $city = '';
    /**
     * 州、省
     *
     * Generated from protobuf field <code>string state = 3;</code>
     */
    protected $state = '';
    /**
     * 邮编
     *
     * Generated from protobuf field <code>string postal_code = 4;</code>
     */
    protected $postal_code = '';
    /**
     * 国家
     *
     * Generated from protobuf field <code>string country_code = 5;</code>
     */
    protected $country_code = '';
    /**
     * 是否为住宅
     *
     * Generated from protobuf field <code>bool residential = 6;</code>
     */
    protected $residential = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $street_lines
     *           街道
     *     @type string $city
     *           市
     *     @type string $state
     *           州、省
     *     @type string $postal_code
     *           邮编
     *     @type string $country_code
     *           国家
     *     @type bool $residential
     *           是否为住宅
     * }
     */
    public function __construct($data = NULL) {
        \Carrier\Fedex\Fedex::initOnce();
        parent::__construct($data);
    }

    /**
     * 街道
     *
     * Generated from protobuf field <code>repeated string street_lines = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getStreetLines()
    {
        return $this->street_lines;
    }

    /**
     * 街道
     *
     * Generated from protobuf field <code>repeated string street_lines = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setStreetLines($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->street_lines = $arr;

        return $this;
    }

    /**
     * 市
     *
     * Generated from protobuf field <code>string city = 2;</code>
     * @return string
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * 市
     *
     * Generated from protobuf field <code>string city = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCity($var)
    {
        GPBUtil::checkString($var, True);
        $this->city = $var;

        return $this;
    }

    /**
     * 州、省
     *
     * Generated from protobuf field <code>string state = 3;</code>
     * @return string
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * 州、省
     *
     * Generated from protobuf field <code>string state = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setState($var)
    {
        GPBUtil::checkString($var, True);
        $this->state = $var;

        return $this;
    }

    /**
     * 邮编
     *
     * Generated from protobuf field <code>string postal_code = 4;</code>
     * @return string
     */
    public function getPostalCode()
    {
        return $this->postal_code;
    }

    /**
     * 邮编
     *
     * Generated from protobuf field <code>string postal_code = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPostalCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->postal_code = $var;

        return $this;
    }

    /**
     * 国家
     *
     * Generated from protobuf field <code>string country_code = 5;</code>
     * @return string
     */
    public function getCountryCode()
    {
        return $this->country_code;
    }

    /**
     * 国家
     *
     * Generated from protobuf field <code>string country_code = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setCountryCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->country_code = $var;

        return $this;
    }

    /**
     * 是否为住宅
     *
     * Generated from protobuf field <code>bool residential = 6;</code>
     * @return bool
     */
    public function getResidential()
    {
        return $this->residential;
    }

    /**
     * 是否为住宅
     *
     * Generated from protobuf field <code>bool residential = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setResidential($var)
    {
        GPBUtil::checkBool($var);
        $this->residential = $var;

        return $this;
    }

}

