<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fedex.proto

namespace Carrier\Fedex;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 联系方式
 *
 * Generated from protobuf message <code>fedex.Contact</code>
 */
class Contact extends \Google\Protobuf\Internal\Message
{
    /**
     * 姓名
     *
     * Generated from protobuf field <code>string person_name = 1;</code>
     */
    protected $person_name = '';
    /**
     * 邮箱地址
     *
     * Generated from protobuf field <code>string email_address = 2;</code>
     */
    protected $email_address = '';
    /**
     * 区号
     *
     * Generated from protobuf field <code>string phone_extension = 3;</code>
     */
    protected $phone_extension = '';
    /**
     * 电话
     *
     * Generated from protobuf field <code>string phone_number = 4;</code>
     */
    protected $phone_number = '';
    /**
     * 公司名称
     *
     * Generated from protobuf field <code>string company_name = 5;</code>
     */
    protected $company_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $person_name
     *           姓名
     *     @type string $email_address
     *           邮箱地址
     *     @type string $phone_extension
     *           区号
     *     @type string $phone_number
     *           电话
     *     @type string $company_name
     *           公司名称
     * }
     */
    public function __construct($data = NULL) {
        \Carrier\Fedex\Fedex::initOnce();
        parent::__construct($data);
    }

    /**
     * 姓名
     *
     * Generated from protobuf field <code>string person_name = 1;</code>
     * @return string
     */
    public function getPersonName()
    {
        return $this->person_name;
    }

    /**
     * 姓名
     *
     * Generated from protobuf field <code>string person_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPersonName($var)
    {
        GPBUtil::checkString($var, True);
        $this->person_name = $var;

        return $this;
    }

    /**
     * 邮箱地址
     *
     * Generated from protobuf field <code>string email_address = 2;</code>
     * @return string
     */
    public function getEmailAddress()
    {
        return $this->email_address;
    }

    /**
     * 邮箱地址
     *
     * Generated from protobuf field <code>string email_address = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setEmailAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->email_address = $var;

        return $this;
    }

    /**
     * 区号
     *
     * Generated from protobuf field <code>string phone_extension = 3;</code>
     * @return string
     */
    public function getPhoneExtension()
    {
        return $this->phone_extension;
    }

    /**
     * 区号
     *
     * Generated from protobuf field <code>string phone_extension = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPhoneExtension($var)
    {
        GPBUtil::checkString($var, True);
        $this->phone_extension = $var;

        return $this;
    }

    /**
     * 电话
     *
     * Generated from protobuf field <code>string phone_number = 4;</code>
     * @return string
     */
    public function getPhoneNumber()
    {
        return $this->phone_number;
    }

    /**
     * 电话
     *
     * Generated from protobuf field <code>string phone_number = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPhoneNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->phone_number = $var;

        return $this;
    }

    /**
     * 公司名称
     *
     * Generated from protobuf field <code>string company_name = 5;</code>
     * @return string
     */
    public function getCompanyName()
    {
        return $this->company_name;
    }

    /**
     * 公司名称
     *
     * Generated from protobuf field <code>string company_name = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setCompanyName($var)
    {
        GPBUtil::checkString($var, True);
        $this->company_name = $var;

        return $this;
    }

}

