<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fedex.proto

namespace Carrier\Fedex;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 创建面单请求
 *
 * Generated from protobuf message <code>fedex.CreateShipmentRequest</code>
 */
class CreateShipmentRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.fedex.Auth authorization = 1;</code>
     */
    protected $authorization = null;
    /**
     * Generated from protobuf field <code>.fedex.RequestedShipment requested_shipment = 2;</code>
     */
    protected $requested_shipment = null;
    /**
     * Generated from protobuf field <code>.fedex.CreateShipmentRequest.LabelResponseOptions label_response_options = 3;</code>
     */
    protected $label_response_options = 0;
    /**
     * Generated from protobuf field <code>string account_number = 4;</code>
     */
    protected $account_number = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Carrier\Fedex\Auth $authorization
     *     @type \Carrier\Fedex\RequestedShipment $requested_shipment
     *     @type int $label_response_options
     *     @type string $account_number
     * }
     */
    public function __construct($data = NULL) {
        \Carrier\Fedex\Fedex::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.fedex.Auth authorization = 1;</code>
     * @return \Carrier\Fedex\Auth|null
     */
    public function getAuthorization()
    {
        return $this->authorization;
    }

    public function hasAuthorization()
    {
        return isset($this->authorization);
    }

    public function clearAuthorization()
    {
        unset($this->authorization);
    }

    /**
     * Generated from protobuf field <code>.fedex.Auth authorization = 1;</code>
     * @param \Carrier\Fedex\Auth $var
     * @return $this
     */
    public function setAuthorization($var)
    {
        GPBUtil::checkMessage($var, \Carrier\Fedex\Auth::class);
        $this->authorization = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.fedex.RequestedShipment requested_shipment = 2;</code>
     * @return \Carrier\Fedex\RequestedShipment|null
     */
    public function getRequestedShipment()
    {
        return $this->requested_shipment;
    }

    public function hasRequestedShipment()
    {
        return isset($this->requested_shipment);
    }

    public function clearRequestedShipment()
    {
        unset($this->requested_shipment);
    }

    /**
     * Generated from protobuf field <code>.fedex.RequestedShipment requested_shipment = 2;</code>
     * @param \Carrier\Fedex\RequestedShipment $var
     * @return $this
     */
    public function setRequestedShipment($var)
    {
        GPBUtil::checkMessage($var, \Carrier\Fedex\RequestedShipment::class);
        $this->requested_shipment = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.fedex.CreateShipmentRequest.LabelResponseOptions label_response_options = 3;</code>
     * @return int
     */
    public function getLabelResponseOptions()
    {
        return $this->label_response_options;
    }

    /**
     * Generated from protobuf field <code>.fedex.CreateShipmentRequest.LabelResponseOptions label_response_options = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setLabelResponseOptions($var)
    {
        GPBUtil::checkEnum($var, \Carrier\Fedex\CreateShipmentRequest\LabelResponseOptions::class);
        $this->label_response_options = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string account_number = 4;</code>
     * @return string
     */
    public function getAccountNumber()
    {
        return $this->account_number;
    }

    /**
     * Generated from protobuf field <code>string account_number = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setAccountNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->account_number = $var;

        return $this;
    }

}

