<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fedex.proto

namespace Carrier\Fedex;

if (false) {
    /**
     * This class is deprecated. Use Carrier\Fedex\CreateShipmentRequest\LabelResponseOptions instead.
     * @deprecated
     */
    class CreateShipmentRequest_LabelResponseOptions {}
}
class_exists(CreateShipmentRequest\LabelResponseOptions::class);
@trigger_error('Carrier\Fedex\CreateShipmentRequest_LabelResponseOptions is deprecated and will be removed in the next major release. Use Carrier\Fedex\CreateShipmentRequest\LabelResponseOptions instead', E_USER_DEPRECATED);

