<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fedex.proto

namespace Carrier\Fedex;

if (false) {
    /**
     * This class is deprecated. Use Carrier\Fedex\CustomerReferences\CustomerReferenceType instead.
     * @deprecated
     */
    class CustomerReferences_CustomerReferenceType {}
}
class_exists(CustomerReferences\CustomerReferenceType::class);
@trigger_error('Carrier\Fedex\CustomerReferences_CustomerReferenceType is deprecated and will be removed in the next major release. Use Carrier\Fedex\CustomerReferences\CustomerReferenceType instead', E_USER_DEPRECATED);

