<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fedex.proto

namespace Carrier\Fedex;

if (false) {
    /**
     * This class is deprecated. Use Carrier\Fedex\LabelSpecification\ImageType instead.
     * @deprecated
     */
    class LabelSpecification_ImageType {}
}
class_exists(LabelSpecification\ImageType::class);
@trigger_error('Carrier\Fedex\LabelSpecification_ImageType is deprecated and will be removed in the next major release. Use Carrier\Fedex\LabelSpecification\ImageType instead', E_USER_DEPRECATED);

