<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fedex.proto

namespace Carrier\Fedex;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 标签规范细节
 *
 * Generated from protobuf message <code>fedex.LabelSpecification</code>
 */
class LabelSpecification extends \Google\Protobuf\Internal\Message
{
    /**
     * 指示使用的标签库存类型
     *
     * Generated from protobuf field <code>.fedex.LabelSpecification.LabelStockType label_stock_type = 1;</code>
     */
    protected $label_stock_type = 0;
    /**
     * 指定发货文档使用的图像格式
     *
     * Generated from protobuf field <code>.fedex.LabelSpecification.ImageType image_type = 2;</code>
     */
    protected $image_type = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $label_stock_type
     *           指示使用的标签库存类型
     *     @type int $image_type
     *           指定发货文档使用的图像格式
     * }
     */
    public function __construct($data = NULL) {
        \Carrier\Fedex\Fedex::initOnce();
        parent::__construct($data);
    }

    /**
     * 指示使用的标签库存类型
     *
     * Generated from protobuf field <code>.fedex.LabelSpecification.LabelStockType label_stock_type = 1;</code>
     * @return int
     */
    public function getLabelStockType()
    {
        return $this->label_stock_type;
    }

    /**
     * 指示使用的标签库存类型
     *
     * Generated from protobuf field <code>.fedex.LabelSpecification.LabelStockType label_stock_type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setLabelStockType($var)
    {
        GPBUtil::checkEnum($var, \Carrier\Fedex\LabelSpecification\LabelStockType::class);
        $this->label_stock_type = $var;

        return $this;
    }

    /**
     * 指定发货文档使用的图像格式
     *
     * Generated from protobuf field <code>.fedex.LabelSpecification.ImageType image_type = 2;</code>
     * @return int
     */
    public function getImageType()
    {
        return $this->image_type;
    }

    /**
     * 指定发货文档使用的图像格式
     *
     * Generated from protobuf field <code>.fedex.LabelSpecification.ImageType image_type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setImageType($var)
    {
        GPBUtil::checkEnum($var, \Carrier\Fedex\LabelSpecification\ImageType::class);
        $this->image_type = $var;

        return $this;
    }

}

