<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fedex.proto

namespace Carrier\Fedex;

if (false) {
    /**
     * This class is deprecated. Use Carrier\Fedex\LabelSpecification\LabelStockType instead.
     * @deprecated
     */
    class LabelSpecification_LabelStockType {}
}
class_exists(LabelSpecification\LabelStockType::class);
@trigger_error('Carrier\Fedex\LabelSpecification_LabelStockType is deprecated and will be removed in the next major release. Use Carrier\Fedex\LabelSpecification\LabelStockType instead', E_USER_DEPRECATED);

