<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fedex.proto

namespace Carrier\Fedex;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 联系人
 *
 * Generated from protobuf message <code>fedex.Linkman</code>
 */
class Linkman extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.fedex.Address address = 1;</code>
     */
    protected $address = null;
    /**
     * Generated from protobuf field <code>.fedex.Contact contact = 2;</code>
     */
    protected $contact = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Carrier\Fedex\Address $address
     *     @type \Carrier\Fedex\Contact $contact
     * }
     */
    public function __construct($data = NULL) {
        \Carrier\Fedex\Fedex::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.fedex.Address address = 1;</code>
     * @return \Carrier\Fedex\Address|null
     */
    public function getAddress()
    {
        return $this->address;
    }

    public function hasAddress()
    {
        return isset($this->address);
    }

    public function clearAddress()
    {
        unset($this->address);
    }

    /**
     * Generated from protobuf field <code>.fedex.Address address = 1;</code>
     * @param \Carrier\Fedex\Address $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkMessage($var, \Carrier\Fedex\Address::class);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.fedex.Contact contact = 2;</code>
     * @return \Carrier\Fedex\Contact|null
     */
    public function getContact()
    {
        return $this->contact;
    }

    public function hasContact()
    {
        return isset($this->contact);
    }

    public function clearContact()
    {
        unset($this->contact);
    }

    /**
     * Generated from protobuf field <code>.fedex.Contact contact = 2;</code>
     * @param \Carrier\Fedex\Contact $var
     * @return $this
     */
    public function setContact($var)
    {
        GPBUtil::checkMessage($var, \Carrier\Fedex\Contact::class);
        $this->contact = $var;

        return $this;
    }

}

