<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fedex.proto

namespace Carrier\Fedex;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 付款人信息
 *
 * Generated from protobuf message <code>fedex.Payor</code>
 */
class Payor extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.fedex.ResponsibleParty responsible_party = 1;</code>
     */
    protected $responsible_party = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Carrier\Fedex\ResponsibleParty $responsible_party
     * }
     */
    public function __construct($data = NULL) {
        \Carrier\Fedex\Fedex::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.fedex.ResponsibleParty responsible_party = 1;</code>
     * @return \Carrier\Fedex\ResponsibleParty|null
     */
    public function getResponsibleParty()
    {
        return $this->responsible_party;
    }

    public function hasResponsibleParty()
    {
        return isset($this->responsible_party);
    }

    public function clearResponsibleParty()
    {
        unset($this->responsible_party);
    }

    /**
     * Generated from protobuf field <code>.fedex.ResponsibleParty responsible_party = 1;</code>
     * @param \Carrier\Fedex\ResponsibleParty $var
     * @return $this
     */
    public function setResponsibleParty($var)
    {
        GPBUtil::checkMessage($var, \Carrier\Fedex\ResponsibleParty::class);
        $this->responsible_party = $var;

        return $this;
    }

}

