<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fedex.proto

namespace Carrier\Fedex;

if (false) {
    /**
     * This class is deprecated. Use Carrier\Fedex\RequestedShipment\PackagingType instead.
     * @deprecated
     */
    class RequestedShipment_PackagingType {}
}
class_exists(RequestedShipment\PackagingType::class);
@trigger_error('Carrier\Fedex\RequestedShipment_PackagingType is deprecated and will be removed in the next major release. Use Carrier\Fedex\RequestedShipment\PackagingType instead', E_USER_DEPRECATED);

