<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fedex.proto

namespace Carrier\Fedex;

if (false) {
    /**
     * This class is deprecated. Use Carrier\Fedex\RequestedShipment\PickupType instead.
     * @deprecated
     */
    class RequestedShipment_PickupType {}
}
class_exists(RequestedShipment\PickupType::class);
@trigger_error('Carrier\Fedex\RequestedShipment_PickupType is deprecated and will be removed in the next major release. Use Carrier\Fedex\RequestedShipment\PickupType instead', E_USER_DEPRECATED);

