<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fedex.proto

namespace Carrier\Fedex;

if (false) {
    /**
     * This class is deprecated. Use Carrier\Fedex\RequestedShipment\ServiceType instead.
     * @deprecated
     */
    class RequestedShipment_ServiceType {}
}
class_exists(RequestedShipment\ServiceType::class);
@trigger_error('Carrier\Fedex\RequestedShipment_ServiceType is deprecated and will be removed in the next major release. Use Carrier\Fedex\RequestedShipment\ServiceType instead', E_USER_DEPRECATED);

