<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fedex.proto

namespace Carrier\Fedex;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 单个包裹信息
 *
 * Generated from protobuf message <code>fedex.RequestedPackageLineItems</code>
 */
class RequestedPackageLineItems extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.fedex.Weight weight = 1;</code>
     */
    protected $weight = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Carrier\Fedex\Weight $weight
     * }
     */
    public function __construct($data = NULL) {
        \Carrier\Fedex\Fedex::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.fedex.Weight weight = 1;</code>
     * @return \Carrier\Fedex\Weight|null
     */
    public function getWeight()
    {
        return $this->weight;
    }

    public function hasWeight()
    {
        return isset($this->weight);
    }

    public function clearWeight()
    {
        unset($this->weight);
    }

    /**
     * Generated from protobuf field <code>.fedex.Weight weight = 1;</code>
     * @param \Carrier\Fedex\Weight $var
     * @return $this
     */
    public function setWeight($var)
    {
        GPBUtil::checkMessage($var, \Carrier\Fedex\Weight::class);
        $this->weight = $var;

        return $this;
    }

}

