<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fedex.proto

namespace Carrier\Fedex;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 单个包裹信息
 *
 * Generated from protobuf message <code>fedex.RequestedPackageLineItems</code>
 */
class RequestedPackageLineItems extends \Google\Protobuf\Internal\Message
{
    /**
     * 重量
     *
     * Generated from protobuf field <code>.fedex.Weight weight = 1;</code>
     */
    protected $weight = null;
    /**
     * 客户引用
     *
     * Generated from protobuf field <code>repeated .fedex.CustomerReferences customer_references = 2;</code>
     */
    private $customer_references;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Carrier\Fedex\Weight $weight
     *           重量
     *     @type \Carrier\Fedex\CustomerReferences[]|\Google\Protobuf\Internal\RepeatedField $customer_references
     *           客户引用
     * }
     */
    public function __construct($data = NULL) {
        \Carrier\Fedex\Fedex::initOnce();
        parent::__construct($data);
    }

    /**
     * 重量
     *
     * Generated from protobuf field <code>.fedex.Weight weight = 1;</code>
     * @return \Carrier\Fedex\Weight|null
     */
    public function getWeight()
    {
        return $this->weight;
    }

    public function hasWeight()
    {
        return isset($this->weight);
    }

    public function clearWeight()
    {
        unset($this->weight);
    }

    /**
     * 重量
     *
     * Generated from protobuf field <code>.fedex.Weight weight = 1;</code>
     * @param \Carrier\Fedex\Weight $var
     * @return $this
     */
    public function setWeight($var)
    {
        GPBUtil::checkMessage($var, \Carrier\Fedex\Weight::class);
        $this->weight = $var;

        return $this;
    }

    /**
     * 客户引用
     *
     * Generated from protobuf field <code>repeated .fedex.CustomerReferences customer_references = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCustomerReferences()
    {
        return $this->customer_references;
    }

    /**
     * 客户引用
     *
     * Generated from protobuf field <code>repeated .fedex.CustomerReferences customer_references = 2;</code>
     * @param \Carrier\Fedex\CustomerReferences[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCustomerReferences($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Carrier\Fedex\CustomerReferences::class);
        $this->customer_references = $arr;

        return $this;
    }

}

