<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fedex.proto

namespace Carrier\Fedex;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 所要求的货物的描述数据
 *
 * Generated from protobuf message <code>fedex.RequestedShipment</code>
 */
class RequestedShipment extends \Google\Protobuf\Internal\Message
{
    /**
     * 托运人
     *
     * Generated from protobuf field <code>.fedex.Linkman shipper = 1;</code>
     */
    protected $shipper = null;
    /**
     * 收件人
     *
     * Generated from protobuf field <code>repeated .fedex.Linkman recipients = 2;</code>
     */
    private $recipients;
    /**
     * 指定提货方式
     *
     * Generated from protobuf field <code>.fedex.RequestedShipment.PickupType pickup_type = 3;</code>
     */
    protected $pickup_type = 0;
    /**
     * 指定服务类型
     *
     * Generated from protobuf field <code>.fedex.RequestedShipment.ServiceType service_type = 4;</code>
     */
    protected $service_type = 0;
    /**
     * 指定使用的包装(默认YOUR_PACKAGING)
     *
     * Generated from protobuf field <code>.fedex.RequestedShipment.PackagingType packaging_type = 5;</code>
     */
    protected $packaging_type = 0;
    /**
     * 指定支付细节，指定支付联邦快递提供运输服务的方法和方式。
     *
     * Generated from protobuf field <code>.fedex.ShippingChargesPayment shipping_charges_payment = 6;</code>
     */
    protected $shipping_charges_payment = null;
    /**
     * 指示使用的标签规范细节
     *
     * Generated from protobuf field <code>.fedex.LabelSpecification label_specification = 7;</code>
     */
    protected $label_specification = null;
    /**
     * 一个或多个包装属性描述
     *
     * Generated from protobuf field <code>repeated .fedex.RequestedPackageLineItems requested_package_line_items = 8;</code>
     */
    private $requested_package_line_items;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Carrier\Fedex\Linkman $shipper
     *           托运人
     *     @type \Carrier\Fedex\Linkman[]|\Google\Protobuf\Internal\RepeatedField $recipients
     *           收件人
     *     @type int $pickup_type
     *           指定提货方式
     *     @type int $service_type
     *           指定服务类型
     *     @type int $packaging_type
     *           指定使用的包装(默认YOUR_PACKAGING)
     *     @type \Carrier\Fedex\ShippingChargesPayment $shipping_charges_payment
     *           指定支付细节，指定支付联邦快递提供运输服务的方法和方式。
     *     @type \Carrier\Fedex\LabelSpecification $label_specification
     *           指示使用的标签规范细节
     *     @type \Carrier\Fedex\RequestedPackageLineItems[]|\Google\Protobuf\Internal\RepeatedField $requested_package_line_items
     *           一个或多个包装属性描述
     * }
     */
    public function __construct($data = NULL) {
        \Carrier\Fedex\Fedex::initOnce();
        parent::__construct($data);
    }

    /**
     * 托运人
     *
     * Generated from protobuf field <code>.fedex.Linkman shipper = 1;</code>
     * @return \Carrier\Fedex\Linkman|null
     */
    public function getShipper()
    {
        return $this->shipper;
    }

    public function hasShipper()
    {
        return isset($this->shipper);
    }

    public function clearShipper()
    {
        unset($this->shipper);
    }

    /**
     * 托运人
     *
     * Generated from protobuf field <code>.fedex.Linkman shipper = 1;</code>
     * @param \Carrier\Fedex\Linkman $var
     * @return $this
     */
    public function setShipper($var)
    {
        GPBUtil::checkMessage($var, \Carrier\Fedex\Linkman::class);
        $this->shipper = $var;

        return $this;
    }

    /**
     * 收件人
     *
     * Generated from protobuf field <code>repeated .fedex.Linkman recipients = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRecipients()
    {
        return $this->recipients;
    }

    /**
     * 收件人
     *
     * Generated from protobuf field <code>repeated .fedex.Linkman recipients = 2;</code>
     * @param \Carrier\Fedex\Linkman[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRecipients($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Carrier\Fedex\Linkman::class);
        $this->recipients = $arr;

        return $this;
    }

    /**
     * 指定提货方式
     *
     * Generated from protobuf field <code>.fedex.RequestedShipment.PickupType pickup_type = 3;</code>
     * @return int
     */
    public function getPickupType()
    {
        return $this->pickup_type;
    }

    /**
     * 指定提货方式
     *
     * Generated from protobuf field <code>.fedex.RequestedShipment.PickupType pickup_type = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setPickupType($var)
    {
        GPBUtil::checkEnum($var, \Carrier\Fedex\RequestedShipment\PickupType::class);
        $this->pickup_type = $var;

        return $this;
    }

    /**
     * 指定服务类型
     *
     * Generated from protobuf field <code>.fedex.RequestedShipment.ServiceType service_type = 4;</code>
     * @return int
     */
    public function getServiceType()
    {
        return $this->service_type;
    }

    /**
     * 指定服务类型
     *
     * Generated from protobuf field <code>.fedex.RequestedShipment.ServiceType service_type = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setServiceType($var)
    {
        GPBUtil::checkEnum($var, \Carrier\Fedex\RequestedShipment\ServiceType::class);
        $this->service_type = $var;

        return $this;
    }

    /**
     * 指定使用的包装(默认YOUR_PACKAGING)
     *
     * Generated from protobuf field <code>.fedex.RequestedShipment.PackagingType packaging_type = 5;</code>
     * @return int
     */
    public function getPackagingType()
    {
        return $this->packaging_type;
    }

    /**
     * 指定使用的包装(默认YOUR_PACKAGING)
     *
     * Generated from protobuf field <code>.fedex.RequestedShipment.PackagingType packaging_type = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setPackagingType($var)
    {
        GPBUtil::checkEnum($var, \Carrier\Fedex\RequestedShipment\PackagingType::class);
        $this->packaging_type = $var;

        return $this;
    }

    /**
     * 指定支付细节，指定支付联邦快递提供运输服务的方法和方式。
     *
     * Generated from protobuf field <code>.fedex.ShippingChargesPayment shipping_charges_payment = 6;</code>
     * @return \Carrier\Fedex\ShippingChargesPayment|null
     */
    public function getShippingChargesPayment()
    {
        return $this->shipping_charges_payment;
    }

    public function hasShippingChargesPayment()
    {
        return isset($this->shipping_charges_payment);
    }

    public function clearShippingChargesPayment()
    {
        unset($this->shipping_charges_payment);
    }

    /**
     * 指定支付细节，指定支付联邦快递提供运输服务的方法和方式。
     *
     * Generated from protobuf field <code>.fedex.ShippingChargesPayment shipping_charges_payment = 6;</code>
     * @param \Carrier\Fedex\ShippingChargesPayment $var
     * @return $this
     */
    public function setShippingChargesPayment($var)
    {
        GPBUtil::checkMessage($var, \Carrier\Fedex\ShippingChargesPayment::class);
        $this->shipping_charges_payment = $var;

        return $this;
    }

    /**
     * 指示使用的标签规范细节
     *
     * Generated from protobuf field <code>.fedex.LabelSpecification label_specification = 7;</code>
     * @return \Carrier\Fedex\LabelSpecification|null
     */
    public function getLabelSpecification()
    {
        return $this->label_specification;
    }

    public function hasLabelSpecification()
    {
        return isset($this->label_specification);
    }

    public function clearLabelSpecification()
    {
        unset($this->label_specification);
    }

    /**
     * 指示使用的标签规范细节
     *
     * Generated from protobuf field <code>.fedex.LabelSpecification label_specification = 7;</code>
     * @param \Carrier\Fedex\LabelSpecification $var
     * @return $this
     */
    public function setLabelSpecification($var)
    {
        GPBUtil::checkMessage($var, \Carrier\Fedex\LabelSpecification::class);
        $this->label_specification = $var;

        return $this;
    }

    /**
     * 一个或多个包装属性描述
     *
     * Generated from protobuf field <code>repeated .fedex.RequestedPackageLineItems requested_package_line_items = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRequestedPackageLineItems()
    {
        return $this->requested_package_line_items;
    }

    /**
     * 一个或多个包装属性描述
     *
     * Generated from protobuf field <code>repeated .fedex.RequestedPackageLineItems requested_package_line_items = 8;</code>
     * @param \Carrier\Fedex\RequestedPackageLineItems[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRequestedPackageLineItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Carrier\Fedex\RequestedPackageLineItems::class);
        $this->requested_package_line_items = $arr;

        return $this;
    }

}

