<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fedex.proto

namespace Carrier\Fedex;

if (false) {
    /**
     * This class is deprecated. Use Carrier\Fedex\ShippingChargesPayment\PaymentType instead.
     * @deprecated
     */
    class ShippingChargesPayment_PaymentType {}
}
class_exists(ShippingChargesPayment\PaymentType::class);
@trigger_error('Carrier\Fedex\ShippingChargesPayment_PaymentType is deprecated and will be removed in the next major release. Use Carrier\Fedex\ShippingChargesPayment\PaymentType instead', E_USER_DEPRECATED);

