<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fedex.proto

namespace Carrier\Fedex;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 支付细节
 *
 * Generated from protobuf message <code>fedex.ShippingChargesPayment</code>
 */
class ShippingChargesPayment extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.fedex.ShippingChargesPayment.PaymentType payment_type = 1;</code>
     */
    protected $payment_type = 0;
    /**
     * Generated from protobuf field <code>string account_number = 2;</code>
     */
    protected $account_number = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $payment_type
     *     @type string $account_number
     * }
     */
    public function __construct($data = NULL) {
        \Carrier\Fedex\Fedex::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.fedex.ShippingChargesPayment.PaymentType payment_type = 1;</code>
     * @return int
     */
    public function getPaymentType()
    {
        return $this->payment_type;
    }

    /**
     * Generated from protobuf field <code>.fedex.ShippingChargesPayment.PaymentType payment_type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPaymentType($var)
    {
        GPBUtil::checkEnum($var, \Carrier\Fedex\ShippingChargesPayment\PaymentType::class);
        $this->payment_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string account_number = 2;</code>
     * @return string
     */
    public function getAccountNumber()
    {
        return $this->account_number;
    }

    /**
     * Generated from protobuf field <code>string account_number = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAccountNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->account_number = $var;

        return $this;
    }

}

