<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fedex.proto

namespace Carrier\Fedex;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * smart post发货详细信息
 *
 * Generated from protobuf message <code>fedex.SmartPostInfoDetail</code>
 */
class SmartPostInfoDetail extends \Google\Protobuf\Internal\Message
{
    /**
     * 指定用于智能端口发货的四位数字集线器ID值。
     *
     * Generated from protobuf field <code>string hub_id = 1;</code>
     */
    protected $hub_id = '';
    /**
     * Generated from protobuf field <code>.fedex.SmartPostInfoDetail.Indicia indicia = 2;</code>
     */
    protected $indicia = 0;
    /**
     * Generated from protobuf field <code>.fedex.SmartPostInfoDetail.AncillaryEndorsement ancillaryEndorsement = 3;</code>
     */
    protected $ancillaryEndorsement = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $hub_id
     *           指定用于智能端口发货的四位数字集线器ID值。
     *     @type int $indicia
     *     @type int $ancillaryEndorsement
     * }
     */
    public function __construct($data = NULL) {
        \Carrier\Fedex\Fedex::initOnce();
        parent::__construct($data);
    }

    /**
     * 指定用于智能端口发货的四位数字集线器ID值。
     *
     * Generated from protobuf field <code>string hub_id = 1;</code>
     * @return string
     */
    public function getHubId()
    {
        return $this->hub_id;
    }

    /**
     * 指定用于智能端口发货的四位数字集线器ID值。
     *
     * Generated from protobuf field <code>string hub_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setHubId($var)
    {
        GPBUtil::checkString($var, True);
        $this->hub_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.fedex.SmartPostInfoDetail.Indicia indicia = 2;</code>
     * @return int
     */
    public function getIndicia()
    {
        return $this->indicia;
    }

    /**
     * Generated from protobuf field <code>.fedex.SmartPostInfoDetail.Indicia indicia = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setIndicia($var)
    {
        GPBUtil::checkEnum($var, \Carrier\Fedex\SmartPostInfoDetail\Indicia::class);
        $this->indicia = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.fedex.SmartPostInfoDetail.AncillaryEndorsement ancillaryEndorsement = 3;</code>
     * @return int
     */
    public function getAncillaryEndorsement()
    {
        return $this->ancillaryEndorsement;
    }

    /**
     * Generated from protobuf field <code>.fedex.SmartPostInfoDetail.AncillaryEndorsement ancillaryEndorsement = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setAncillaryEndorsement($var)
    {
        GPBUtil::checkEnum($var, \Carrier\Fedex\SmartPostInfoDetail\AncillaryEndorsement::class);
        $this->ancillaryEndorsement = $var;

        return $this;
    }

}

