<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fedex.proto

namespace Carrier\Fedex;

if (false) {
    /**
     * This class is deprecated. Use Carrier\Fedex\SmartPostInfoDetail\AncillaryEndorsement instead.
     * @deprecated
     */
    class SmartPostInfoDetail_AncillaryEndorsement {}
}
class_exists(SmartPostInfoDetail\AncillaryEndorsement::class);
@trigger_error('Carrier\Fedex\SmartPostInfoDetail_AncillaryEndorsement is deprecated and will be removed in the next major release. Use Carrier\Fedex\SmartPostInfoDetail\AncillaryEndorsement instead', E_USER_DEPRECATED);

