<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fedex.proto

namespace Carrier\Fedex;

if (false) {
    /**
     * This class is deprecated. Use Carrier\Fedex\SmartPostInfoDetail\Indicia instead.
     * @deprecated
     */
    class SmartPostInfoDetail_Indicia {}
}
class_exists(SmartPostInfoDetail\Indicia::class);
@trigger_error('Carrier\Fedex\SmartPostInfoDetail_Indicia is deprecated and will be removed in the next major release. Use Carrier\Fedex\SmartPostInfoDetail\Indicia instead', E_USER_DEPRECATED);

