<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fedex.proto

namespace Carrier\Fedex;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 物流跟踪请求
 *
 * Generated from protobuf message <code>fedex.TrackRequest</code>
 */
class TrackRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.fedex.Auth authorization = 1;</code>
     */
    protected $authorization = null;
    /**
     * Generated from protobuf field <code>string track_number = 2;</code>
     */
    protected $track_number = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Carrier\Fedex\Auth $authorization
     *     @type string $track_number
     * }
     */
    public function __construct($data = NULL) {
        \Carrier\Fedex\Fedex::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.fedex.Auth authorization = 1;</code>
     * @return \Carrier\Fedex\Auth|null
     */
    public function getAuthorization()
    {
        return $this->authorization;
    }

    public function hasAuthorization()
    {
        return isset($this->authorization);
    }

    public function clearAuthorization()
    {
        unset($this->authorization);
    }

    /**
     * Generated from protobuf field <code>.fedex.Auth authorization = 1;</code>
     * @param \Carrier\Fedex\Auth $var
     * @return $this
     */
    public function setAuthorization($var)
    {
        GPBUtil::checkMessage($var, \Carrier\Fedex\Auth::class);
        $this->authorization = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string track_number = 2;</code>
     * @return string
     */
    public function getTrackNumber()
    {
        return $this->track_number;
    }

    /**
     * Generated from protobuf field <code>string track_number = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTrackNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->track_number = $var;

        return $this;
    }

}

