<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fedex.proto

namespace Carrier\Fedex;

if (false) {
    /**
     * This class is deprecated. Use Carrier\Fedex\Weight\Unit instead.
     * @deprecated
     */
    class Weight_Unit {}
}
class_exists(Weight\Unit::class);
@trigger_error('Carrier\Fedex\Weight_Unit is deprecated and will be removed in the next major release. Use Carrier\Fedex\Weight\Unit instead', E_USER_DEPRECATED);

