<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fedex.proto

namespace Carrier\Fedex\CreateShipmentRequest;

use UnexpectedValueException;

/**
 * 标签返回类型枚举(编码或标签URL)
 *
 * Protobuf type <code>fedex.CreateShipmentRequest.LabelResponseOptions</code>
 */
class LabelResponseOptions
{
    /**
     * Generated from protobuf enum <code>URL_ONLY = 0;</code>
     */
    const URL_ONLY = 0;
    /**
     * Generated from protobuf enum <code>LABEL = 1;</code>
     */
    const LABEL = 1;

    private static $valueToName = [
        self::URL_ONLY => 'URL_ONLY',
        self::LABEL => 'LABEL',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(LabelResponseOptions::class, \Carrier\Fedex\CreateShipmentRequest_LabelResponseOptions::class);

