<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ups.proto

namespace Carrier\Ups\Payment;

use UnexpectedValueException;

/**
 * Protobuf type <code>pb.Payment.Type</code>
 */
class Type
{
    /**
     * Generated from protobuf enum <code>PREPAID = 0;</code>
     */
    const PREPAID = 0;
    /**
     * Generated from protobuf enum <code>THIRD_PARTY = 1;</code>
     */
    const THIRD_PARTY = 1;

    private static $valueToName = [
        self::PREPAID => 'PREPAID',
        self::THIRD_PARTY => 'THIRD_PARTY',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Type::class, \Carrier\Ups\Payment_Type::class);

