<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ups.proto

namespace Carrier\Ups;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *包裹
 *
 * Generated from protobuf message <code>pb.Package</code>
 */
class Package extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.pb.PackageType type = 1;</code>
     */
    protected $type = 0;
    /**
     * Generated from protobuf field <code>.pb.Dimensions dimensions = 2;</code>
     */
    protected $dimensions = null;
    /**
     * Generated from protobuf field <code>.pb.Weight weight = 3;</code>
     */
    protected $weight = null;
    /**
     * Generated from protobuf field <code>repeated .pb.Reference references = 4;</code>
     */
    private $references;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *     @type \Carrier\Ups\Dimensions $dimensions
     *     @type \Carrier\Ups\Weight $weight
     *     @type \Carrier\Ups\Reference[]|\Google\Protobuf\Internal\RepeatedField $references
     * }
     */
    public function __construct($data = NULL) {
        \Carrier\Ups\Ups::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.pb.PackageType type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.pb.PackageType type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Carrier\Ups\PackageType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pb.Dimensions dimensions = 2;</code>
     * @return \Carrier\Ups\Dimensions|null
     */
    public function getDimensions()
    {
        return $this->dimensions;
    }

    public function hasDimensions()
    {
        return isset($this->dimensions);
    }

    public function clearDimensions()
    {
        unset($this->dimensions);
    }

    /**
     * Generated from protobuf field <code>.pb.Dimensions dimensions = 2;</code>
     * @param \Carrier\Ups\Dimensions $var
     * @return $this
     */
    public function setDimensions($var)
    {
        GPBUtil::checkMessage($var, \Carrier\Ups\Dimensions::class);
        $this->dimensions = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pb.Weight weight = 3;</code>
     * @return \Carrier\Ups\Weight|null
     */
    public function getWeight()
    {
        return $this->weight;
    }

    public function hasWeight()
    {
        return isset($this->weight);
    }

    public function clearWeight()
    {
        unset($this->weight);
    }

    /**
     * Generated from protobuf field <code>.pb.Weight weight = 3;</code>
     * @param \Carrier\Ups\Weight $var
     * @return $this
     */
    public function setWeight($var)
    {
        GPBUtil::checkMessage($var, \Carrier\Ups\Weight::class);
        $this->weight = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pb.Reference references = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getReferences()
    {
        return $this->references;
    }

    /**
     * Generated from protobuf field <code>repeated .pb.Reference references = 4;</code>
     * @param \Carrier\Ups\Reference[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setReferences($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Carrier\Ups\Reference::class);
        $this->references = $arr;

        return $this;
    }

}

