<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ups.proto

namespace Carrier\Ups;

if (false) {
    /**
     * This class is deprecated. Use Carrier\Ups\Payment\Type instead.
     * @deprecated
     */
    class Payment_Type {}
}
class_exists(Payment\Type::class);
@trigger_error('Carrier\Ups\Payment_Type is deprecated and will be removed in the next major release. Use Carrier\Ups\Payment\Type instead', E_USER_DEPRECATED);

