<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ups.proto

namespace Carrier\Ups;

if (false) {
    /**
     * This class is deprecated. Use Carrier\Ups\Shipment\LabelFormat instead.
     * @deprecated
     */
    class Shipment_LabelFormat {}
}
class_exists(Shipment\LabelFormat::class);
@trigger_error('Carrier\Ups\Shipment_LabelFormat is deprecated and will be removed in the next major release. Use Carrier\Ups\Shipment\LabelFormat instead', E_USER_DEPRECATED);

