<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fedex.proto

namespace Carrier\Fedex\LabelSpecification;

use UnexpectedValueException;

/**
 * 图片类型
 *
 * Protobuf type <code>fedex.LabelSpecification.ImageType</code>
 */
class ImageType
{
    /**
     * Generated from protobuf enum <code>ZPLII = 0;</code>
     */
    const ZPLII = 0;
    /**
     * Generated from protobuf enum <code>EPL2 = 1;</code>
     */
    const EPL2 = 1;
    /**
     * Generated from protobuf enum <code>PDF = 2;</code>
     */
    const PDF = 2;
    /**
     * Generated from protobuf enum <code>PNG = 3;</code>
     */
    const PNG = 3;

    private static $valueToName = [
        self::ZPLII => 'ZPLII',
        self::EPL2 => 'EPL2',
        self::PDF => 'PDF',
        self::PNG => 'PNG',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ImageType::class, \Carrier\Fedex\LabelSpecification_ImageType::class);

