<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fedex.proto

namespace Carrier\Fedex\LabelSpecification;

use UnexpectedValueException;

/**
 * 标签库存类型
 *
 * Protobuf type <code>fedex.LabelSpecification.LabelStockType</code>
 */
class LabelStockType
{
    /**
     * Generated from protobuf enum <code>PAPER_4X6 = 0;</code>
     */
    const PAPER_4X6 = 0;

    private static $valueToName = [
        self::PAPER_4X6 => 'PAPER_4X6',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(LabelStockType::class, \Carrier\Fedex\LabelSpecification_LabelStockType::class);

