<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ups.proto

namespace Carrier\Ups\Shipment;

use UnexpectedValueException;

/**
 * Protobuf type <code>ups.Shipment.LabelFormat</code>
 */
class LabelFormat
{
    /**
     * Generated from protobuf enum <code>PNG = 0;</code>
     */
    const PNG = 0;
    /**
     * Generated from protobuf enum <code>ZPL = 1;</code>
     */
    const ZPL = 1;
    /**
     * Generated from protobuf enum <code>EPL = 2;</code>
     */
    const EPL = 2;
    /**
     * Generated from protobuf enum <code>SPL = 3;</code>
     */
    const SPL = 3;

    private static $valueToName = [
        self::PNG => 'PNG',
        self::ZPL => 'ZPL',
        self::EPL => 'EPL',
        self::SPL => 'SPL',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(LabelFormat::class, \Carrier\Ups\Shipment_LabelFormat::class);

