<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rocket.proto

namespace Carrier\Rocket;

if (false) {
    /**
     * This class is deprecated. Use Carrier\Rocket\CarrierAction\Carrier instead.
     * @deprecated
     */
    class CarrierAction_Carrier {}
}
class_exists(CarrierAction\Carrier::class);
@trigger_error('Carrier\Rocket\CarrierAction_Carrier is deprecated and will be removed in the next major release. Use Carrier\Rocket\CarrierAction\Carrier instead', E_USER_DEPRECATED);

