<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rocket.proto

namespace Carrier\Rocket;

if (false) {
    /**
     * This class is deprecated. Use Carrier\Rocket\CarrierAction\Action instead.
     * @deprecated
     */
    class CarrierAction_Action {}
}
class_exists(CarrierAction\Action::class);
@trigger_error('Carrier\Rocket\CarrierAction_Action is deprecated and will be removed in the next major release. Use Carrier\Rocket\CarrierAction\Action instead', E_USER_DEPRECATED);

