<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rocket.proto

namespace Carrier\Rocket;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 承运商和方法名称
 *
 * Generated from protobuf message <code>rocket.CarrierAction</code>
 */
class CarrierAction extends \Google\Protobuf\Internal\Message
{
    /**
     * 承运商
     *
     * Generated from protobuf field <code>.rocket.CarrierAction.Carrier carrier = 1;</code>
     */
    protected $carrier = 0;
    /**
     * 方法名称
     *
     * Generated from protobuf field <code>.rocket.CarrierAction.Action action = 2;</code>
     */
    protected $action = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $carrier
     *           承运商
     *     @type int $action
     *           方法名称
     * }
     */
    public function __construct($data = NULL) {
        \Carrier\Rocket\Rocket::initOnce();
        parent::__construct($data);
    }

    /**
     * 承运商
     *
     * Generated from protobuf field <code>.rocket.CarrierAction.Carrier carrier = 1;</code>
     * @return int
     */
    public function getCarrier()
    {
        return $this->carrier;
    }

    /**
     * 承运商
     *
     * Generated from protobuf field <code>.rocket.CarrierAction.Carrier carrier = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setCarrier($var)
    {
        GPBUtil::checkEnum($var, \Carrier\Rocket\CarrierAction\Carrier::class);
        $this->carrier = $var;

        return $this;
    }

    /**
     * 方法名称
     *
     * Generated from protobuf field <code>.rocket.CarrierAction.Action action = 2;</code>
     * @return int
     */
    public function getAction()
    {
        return $this->action;
    }

    /**
     * 方法名称
     *
     * Generated from protobuf field <code>.rocket.CarrierAction.Action action = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setAction($var)
    {
        GPBUtil::checkEnum($var, \Carrier\Rocket\CarrierAction\Action::class);
        $this->action = $var;

        return $this;
    }

}

