<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rocket.proto

namespace Carrier\Rocket;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 面单参数
 *
 * Generated from protobuf message <code>rocket.LabelParams</code>
 */
class LabelParams extends \Google\Protobuf\Internal\Message
{
    /**
     * 账号密码
     *
     * Generated from protobuf field <code>.rocket.Auth auth = 1;</code>
     */
    protected $auth = null;
    /**
     * 包裹信息
     *
     * Generated from protobuf field <code>repeated .rocket.Packages packages = 2;</code>
     */
    private $packages;
    /**
     * 发货人
     *
     * Generated from protobuf field <code>.rocket.ShipFrom ship_from = 3;</code>
     */
    protected $ship_from = null;
    /**
     * 收货人
     *
     * Generated from protobuf field <code>.rocket.ShipTo ship_to = 4;</code>
     */
    protected $ship_to = null;
    /**
     * 配送方式
     *
     * Generated from protobuf field <code>.rocket.ServiceCode service = 5;</code>
     */
    protected $service = 0;
    /**
     * 参考值
     *
     * Generated from protobuf field <code>string reference_value = 6;</code>
     */
    protected $reference_value = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Carrier\Rocket\Auth $auth
     *           账号密码
     *     @type \Carrier\Rocket\Packages[]|\Google\Protobuf\Internal\RepeatedField $packages
     *           包裹信息
     *     @type \Carrier\Rocket\ShipFrom $ship_from
     *           发货人
     *     @type \Carrier\Rocket\ShipTo $ship_to
     *           收货人
     *     @type int $service
     *           配送方式
     *     @type string $reference_value
     *           参考值
     * }
     */
    public function __construct($data = NULL) {
        \Carrier\Rocket\Rocket::initOnce();
        parent::__construct($data);
    }

    /**
     * 账号密码
     *
     * Generated from protobuf field <code>.rocket.Auth auth = 1;</code>
     * @return \Carrier\Rocket\Auth|null
     */
    public function getAuth()
    {
        return $this->auth;
    }

    public function hasAuth()
    {
        return isset($this->auth);
    }

    public function clearAuth()
    {
        unset($this->auth);
    }

    /**
     * 账号密码
     *
     * Generated from protobuf field <code>.rocket.Auth auth = 1;</code>
     * @param \Carrier\Rocket\Auth $var
     * @return $this
     */
    public function setAuth($var)
    {
        GPBUtil::checkMessage($var, \Carrier\Rocket\Auth::class);
        $this->auth = $var;

        return $this;
    }

    /**
     * 包裹信息
     *
     * Generated from protobuf field <code>repeated .rocket.Packages packages = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPackages()
    {
        return $this->packages;
    }

    /**
     * 包裹信息
     *
     * Generated from protobuf field <code>repeated .rocket.Packages packages = 2;</code>
     * @param \Carrier\Rocket\Packages[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPackages($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Carrier\Rocket\Packages::class);
        $this->packages = $arr;

        return $this;
    }

    /**
     * 发货人
     *
     * Generated from protobuf field <code>.rocket.ShipFrom ship_from = 3;</code>
     * @return \Carrier\Rocket\ShipFrom|null
     */
    public function getShipFrom()
    {
        return $this->ship_from;
    }

    public function hasShipFrom()
    {
        return isset($this->ship_from);
    }

    public function clearShipFrom()
    {
        unset($this->ship_from);
    }

    /**
     * 发货人
     *
     * Generated from protobuf field <code>.rocket.ShipFrom ship_from = 3;</code>
     * @param \Carrier\Rocket\ShipFrom $var
     * @return $this
     */
    public function setShipFrom($var)
    {
        GPBUtil::checkMessage($var, \Carrier\Rocket\ShipFrom::class);
        $this->ship_from = $var;

        return $this;
    }

    /**
     * 收货人
     *
     * Generated from protobuf field <code>.rocket.ShipTo ship_to = 4;</code>
     * @return \Carrier\Rocket\ShipTo|null
     */
    public function getShipTo()
    {
        return $this->ship_to;
    }

    public function hasShipTo()
    {
        return isset($this->ship_to);
    }

    public function clearShipTo()
    {
        unset($this->ship_to);
    }

    /**
     * 收货人
     *
     * Generated from protobuf field <code>.rocket.ShipTo ship_to = 4;</code>
     * @param \Carrier\Rocket\ShipTo $var
     * @return $this
     */
    public function setShipTo($var)
    {
        GPBUtil::checkMessage($var, \Carrier\Rocket\ShipTo::class);
        $this->ship_to = $var;

        return $this;
    }

    /**
     * 配送方式
     *
     * Generated from protobuf field <code>.rocket.ServiceCode service = 5;</code>
     * @return int
     */
    public function getService()
    {
        return $this->service;
    }

    /**
     * 配送方式
     *
     * Generated from protobuf field <code>.rocket.ServiceCode service = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setService($var)
    {
        GPBUtil::checkEnum($var, \Carrier\Rocket\ServiceCode::class);
        $this->service = $var;

        return $this;
    }

    /**
     * 参考值
     *
     * Generated from protobuf field <code>string reference_value = 6;</code>
     * @return string
     */
    public function getReferenceValue()
    {
        return $this->reference_value;
    }

    /**
     * 参考值
     *
     * Generated from protobuf field <code>string reference_value = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setReferenceValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->reference_value = $var;

        return $this;
    }

}

