<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rocket.proto

namespace Carrier\Rocket;

if (false) {
    /**
     * This class is deprecated. Use Carrier\Rocket\Packages\PackagingType instead.
     * @deprecated
     */
    class Packages_PackagingType {}
}
class_exists(Packages\PackagingType::class);
@trigger_error('Carrier\Rocket\Packages_PackagingType is deprecated and will be removed in the next major release. Use Carrier\Rocket\Packages\PackagingType instead', E_USER_DEPRECATED);

