<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rocket.proto

namespace Carrier\Rocket;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 费率
 *
 * Generated from protobuf message <code>rocket.Rates</code>
 */
class Rates extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string desc = 1;</code>
     */
    protected $desc = '';
    /**
     * Generated from protobuf field <code>double rate = 2;</code>
     */
    protected $rate = 0.0;
    /**
     * Generated from protobuf field <code>string currency = 3;</code>
     */
    protected $currency = '';
    /**
     * Generated from protobuf field <code>string service_code = 4;</code>
     */
    protected $service_code = '';
    /**
     * Generated from protobuf field <code>string est_delivery_time = 5;</code>
     */
    protected $est_delivery_time = '';
    /**
     * Generated from protobuf field <code>string package_type = 6;</code>
     */
    protected $package_type = '';
    /**
     * Generated from protobuf field <code>string rate_detail = 7;</code>
     */
    protected $rate_detail = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $desc
     *     @type float $rate
     *     @type string $currency
     *     @type string $service_code
     *     @type string $est_delivery_time
     *     @type string $package_type
     *     @type string $rate_detail
     * }
     */
    public function __construct($data = NULL) {
        \Carrier\Rocket\Rocket::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string desc = 1;</code>
     * @return string
     */
    public function getDesc()
    {
        return $this->desc;
    }

    /**
     * Generated from protobuf field <code>string desc = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDesc($var)
    {
        GPBUtil::checkString($var, True);
        $this->desc = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double rate = 2;</code>
     * @return float
     */
    public function getRate()
    {
        return $this->rate;
    }

    /**
     * Generated from protobuf field <code>double rate = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setRate($var)
    {
        GPBUtil::checkDouble($var);
        $this->rate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string currency = 3;</code>
     * @return string
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     * Generated from protobuf field <code>string currency = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCurrency($var)
    {
        GPBUtil::checkString($var, True);
        $this->currency = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string service_code = 4;</code>
     * @return string
     */
    public function getServiceCode()
    {
        return $this->service_code;
    }

    /**
     * Generated from protobuf field <code>string service_code = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setServiceCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->service_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string est_delivery_time = 5;</code>
     * @return string
     */
    public function getEstDeliveryTime()
    {
        return $this->est_delivery_time;
    }

    /**
     * Generated from protobuf field <code>string est_delivery_time = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setEstDeliveryTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->est_delivery_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string package_type = 6;</code>
     * @return string
     */
    public function getPackageType()
    {
        return $this->package_type;
    }

    /**
     * Generated from protobuf field <code>string package_type = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setPackageType($var)
    {
        GPBUtil::checkString($var, True);
        $this->package_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string rate_detail = 7;</code>
     * @return string
     */
    public function getRateDetail()
    {
        return $this->rate_detail;
    }

    /**
     * Generated from protobuf field <code>string rate_detail = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setRateDetail($var)
    {
        GPBUtil::checkString($var, True);
        $this->rate_detail = $var;

        return $this;
    }

}

