<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rocket.proto

namespace Carrier\Rocket;

if (false) {
    /**
     * This class is deprecated. Use Carrier\Rocket\RateParams\LengthUnit instead.
     * @deprecated
     */
    class RateParams_LengthUnit {}
}
class_exists(RateParams\LengthUnit::class);
@trigger_error('Carrier\Rocket\RateParams_LengthUnit is deprecated and will be removed in the next major release. Use Carrier\Rocket\RateParams\LengthUnit instead', E_USER_DEPRECATED);

