<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rocket.proto

namespace Carrier\Rocket;

if (false) {
    /**
     * This class is deprecated. Use Carrier\Rocket\RateParams\WeightUnit instead.
     * @deprecated
     */
    class RateParams_WeightUnit {}
}
class_exists(RateParams\WeightUnit::class);
@trigger_error('Carrier\Rocket\RateParams_WeightUnit is deprecated and will be removed in the next major release. Use Carrier\Rocket\RateParams\WeightUnit instead', E_USER_DEPRECATED);

