<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rocket.proto

namespace Carrier\Rocket;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 查询费率响应
 *
 * Generated from protobuf message <code>rocket.RatingResponse</code>
 */
class RatingResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .rocket.Rates rates = 1;</code>
     */
    private $rates;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Carrier\Rocket\Rates[]|\Google\Protobuf\Internal\RepeatedField $rates
     * }
     */
    public function __construct($data = NULL) {
        \Carrier\Rocket\Rocket::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .rocket.Rates rates = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRates()
    {
        return $this->rates;
    }

    /**
     * Generated from protobuf field <code>repeated .rocket.Rates rates = 1;</code>
     * @param \Carrier\Rocket\Rates[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRates($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Carrier\Rocket\Rates::class);
        $this->rates = $arr;

        return $this;
    }

}

