<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rocket.proto

namespace Carrier\Rocket;

use UnexpectedValueException;

/**
 * 配送方式枚举
 *
 * Protobuf type <code>rocket.ServiceCode</code>
 */
class ServiceCode
{
    /**
     * Stamps
     *
     * Generated from protobuf enum <code>SERVICE_CODE_US_FC = 0;</code>
     */
    const SERVICE_CODE_US_FC = 0;
    /**
     * Generated from protobuf enum <code>SERVICE_CODE_US_MM = 1;</code>
     */
    const SERVICE_CODE_US_MM = 1;
    /**
     * Generated from protobuf enum <code>SERVICE_CODE_US_PP = 2;</code>
     */
    const SERVICE_CODE_US_PP = 2;
    /**
     * Generated from protobuf enum <code>SERVICE_CODE_US_PM = 3;</code>
     */
    const SERVICE_CODE_US_PM = 3;
    /**
     * Generated from protobuf enum <code>SERVICE_CODE_US_XM = 4;</code>
     */
    const SERVICE_CODE_US_XM = 4;
    /**
     * Generated from protobuf enum <code>SERVICE_CODE_US_EMI = 5;</code>
     */
    const SERVICE_CODE_US_EMI = 5;
    /**
     * Generated from protobuf enum <code>SERVICE_CODE_US_PMI = 6;</code>
     */
    const SERVICE_CODE_US_PMI = 6;
    /**
     * Generated from protobuf enum <code>SERVICE_CODE_US_FCI = 7;</code>
     */
    const SERVICE_CODE_US_FCI = 7;
    /**
     * Generated from protobuf enum <code>SERVICE_CODE_US_CM = 8;</code>
     */
    const SERVICE_CODE_US_CM = 8;
    /**
     * Generated from protobuf enum <code>SERVICE_CODE_US_PS = 9;</code>
     */
    const SERVICE_CODE_US_PS = 9;
    /**
     * Generated from protobuf enum <code>SERVICE_CODE_US_LM = 10;</code>
     */
    const SERVICE_CODE_US_LM = 10;
    /**
     * Generated from protobuf enum <code>SERVICE_CODE_SC_GPE = 11;</code>
     */
    const SERVICE_CODE_SC_GPE = 11;
    /**
     * Generated from protobuf enum <code>SERVICE_CODE_SC_GPP = 12;</code>
     */
    const SERVICE_CODE_SC_GPP = 12;
    /**
     * Generated from protobuf enum <code>SERVICE_CODE_SC_GPESS = 13;</code>
     */
    const SERVICE_CODE_SC_GPESS = 13;
    /**
     * Generated from protobuf enum <code>SERVICE_CODE_SC_GPPSS = 14;</code>
     */
    const SERVICE_CODE_SC_GPPSS = 14;

    private static $valueToName = [
        self::SERVICE_CODE_US_FC => 'SERVICE_CODE_US_FC',
        self::SERVICE_CODE_US_MM => 'SERVICE_CODE_US_MM',
        self::SERVICE_CODE_US_PP => 'SERVICE_CODE_US_PP',
        self::SERVICE_CODE_US_PM => 'SERVICE_CODE_US_PM',
        self::SERVICE_CODE_US_XM => 'SERVICE_CODE_US_XM',
        self::SERVICE_CODE_US_EMI => 'SERVICE_CODE_US_EMI',
        self::SERVICE_CODE_US_PMI => 'SERVICE_CODE_US_PMI',
        self::SERVICE_CODE_US_FCI => 'SERVICE_CODE_US_FCI',
        self::SERVICE_CODE_US_CM => 'SERVICE_CODE_US_CM',
        self::SERVICE_CODE_US_PS => 'SERVICE_CODE_US_PS',
        self::SERVICE_CODE_US_LM => 'SERVICE_CODE_US_LM',
        self::SERVICE_CODE_SC_GPE => 'SERVICE_CODE_SC_GPE',
        self::SERVICE_CODE_SC_GPP => 'SERVICE_CODE_SC_GPP',
        self::SERVICE_CODE_SC_GPESS => 'SERVICE_CODE_SC_GPESS',
        self::SERVICE_CODE_SC_GPPSS => 'SERVICE_CODE_SC_GPPSS',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

