<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rocket.proto

namespace Carrier\Rocket;

/**
 * Protobuf type <code>rocket.Service</code>
 */
interface ServiceInterface
{
    /**
     * Method <code>createLabel</code>
     *
     * @param \Carrier\Rocket\CreateLabelRequest $request
     * @return \Carrier\Rocket\CreateLabelResponse
     */
    public function createLabel(\Carrier\Rocket\CreateLabelRequest $request);

    /**
     * Method <code>rating</code>
     *
     * @param \Carrier\Rocket\RatingRequest $request
     * @return \Carrier\Rocket\RatingResponse
     */
    public function rating(\Carrier\Rocket\RatingRequest $request);

    /**
     * Method <code>track</code>
     *
     * @param \Carrier\Rocket\TrackRequest $request
     * @return \Carrier\Rocket\TrackResponse
     */
    public function track(\Carrier\Rocket\TrackRequest $request);

}

