<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rocket.proto

namespace Carrier\Rocket;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 发货人
 *
 * Generated from protobuf message <code>rocket.ShipFrom</code>
 */
class ShipFrom extends \Google\Protobuf\Internal\Message
{
    /**
     * 名称
     *
     * Generated from protobuf field <code>string shipper = 1;</code>
     */
    protected $shipper = '';
    /**
     * 电话
     *
     * Generated from protobuf field <code>string ship_phone = 3;</code>
     */
    protected $ship_phone = '';
    /**
     * 地址
     *
     * Generated from protobuf field <code>string ship_addr1 = 4;</code>
     */
    protected $ship_addr1 = '';
    /**
     * 城市
     *
     * Generated from protobuf field <code>string ship_city = 5;</code>
     */
    protected $ship_city = '';
    /**
     * 州
     *
     * Generated from protobuf field <code>string ship_state = 6;</code>
     */
    protected $ship_state = '';
    /**
     * 国家
     *
     * Generated from protobuf field <code>string ship_country = 7;</code>
     */
    protected $ship_country = '';
    /**
     * 邮编
     *
     * Generated from protobuf field <code>string ship_code = 8;</code>
     */
    protected $ship_code = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $shipper
     *           名称
     *     @type string $ship_phone
     *           电话
     *     @type string $ship_addr1
     *           地址
     *     @type string $ship_city
     *           城市
     *     @type string $ship_state
     *           州
     *     @type string $ship_country
     *           国家
     *     @type string $ship_code
     *           邮编
     * }
     */
    public function __construct($data = NULL) {
        \Carrier\Rocket\Rocket::initOnce();
        parent::__construct($data);
    }

    /**
     * 名称
     *
     * Generated from protobuf field <code>string shipper = 1;</code>
     * @return string
     */
    public function getShipper()
    {
        return $this->shipper;
    }

    /**
     * 名称
     *
     * Generated from protobuf field <code>string shipper = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setShipper($var)
    {
        GPBUtil::checkString($var, True);
        $this->shipper = $var;

        return $this;
    }

    /**
     * 电话
     *
     * Generated from protobuf field <code>string ship_phone = 3;</code>
     * @return string
     */
    public function getShipPhone()
    {
        return $this->ship_phone;
    }

    /**
     * 电话
     *
     * Generated from protobuf field <code>string ship_phone = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setShipPhone($var)
    {
        GPBUtil::checkString($var, True);
        $this->ship_phone = $var;

        return $this;
    }

    /**
     * 地址
     *
     * Generated from protobuf field <code>string ship_addr1 = 4;</code>
     * @return string
     */
    public function getShipAddr1()
    {
        return $this->ship_addr1;
    }

    /**
     * 地址
     *
     * Generated from protobuf field <code>string ship_addr1 = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setShipAddr1($var)
    {
        GPBUtil::checkString($var, True);
        $this->ship_addr1 = $var;

        return $this;
    }

    /**
     * 城市
     *
     * Generated from protobuf field <code>string ship_city = 5;</code>
     * @return string
     */
    public function getShipCity()
    {
        return $this->ship_city;
    }

    /**
     * 城市
     *
     * Generated from protobuf field <code>string ship_city = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setShipCity($var)
    {
        GPBUtil::checkString($var, True);
        $this->ship_city = $var;

        return $this;
    }

    /**
     * 州
     *
     * Generated from protobuf field <code>string ship_state = 6;</code>
     * @return string
     */
    public function getShipState()
    {
        return $this->ship_state;
    }

    /**
     * 州
     *
     * Generated from protobuf field <code>string ship_state = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setShipState($var)
    {
        GPBUtil::checkString($var, True);
        $this->ship_state = $var;

        return $this;
    }

    /**
     * 国家
     *
     * Generated from protobuf field <code>string ship_country = 7;</code>
     * @return string
     */
    public function getShipCountry()
    {
        return $this->ship_country;
    }

    /**
     * 国家
     *
     * Generated from protobuf field <code>string ship_country = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setShipCountry($var)
    {
        GPBUtil::checkString($var, True);
        $this->ship_country = $var;

        return $this;
    }

    /**
     * 邮编
     *
     * Generated from protobuf field <code>string ship_code = 8;</code>
     * @return string
     */
    public function getShipCode()
    {
        return $this->ship_code;
    }

    /**
     * 邮编
     *
     * Generated from protobuf field <code>string ship_code = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setShipCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->ship_code = $var;

        return $this;
    }

}

