<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rocket.proto

namespace Carrier\Rocket;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 收件人
 *
 * Generated from protobuf message <code>rocket.ShipTo</code>
 */
class ShipTo extends \Google\Protobuf\Internal\Message
{
    /**
     * 名称
     *
     * Generated from protobuf field <code>string to_name = 1;</code>
     */
    protected $to_name = '';
    /**
     * 电话
     *
     * Generated from protobuf field <code>string to_phone = 2;</code>
     */
    protected $to_phone = '';
    /**
     * 地址
     *
     * Generated from protobuf field <code>string to_addr1 = 3;</code>
     */
    protected $to_addr1 = '';
    /**
     * 城市
     *
     * Generated from protobuf field <code>string to_city = 4;</code>
     */
    protected $to_city = '';
    /**
     * 州
     *
     * Generated from protobuf field <code>string to_state = 5;</code>
     */
    protected $to_state = '';
    /**
     * 国家
     *
     * Generated from protobuf field <code>string to_country = 6;</code>
     */
    protected $to_country = '';
    /**
     * 邮编
     *
     * Generated from protobuf field <code>string to_code = 7;</code>
     */
    protected $to_code = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $to_name
     *           名称
     *     @type string $to_phone
     *           电话
     *     @type string $to_addr1
     *           地址
     *     @type string $to_city
     *           城市
     *     @type string $to_state
     *           州
     *     @type string $to_country
     *           国家
     *     @type string $to_code
     *           邮编
     * }
     */
    public function __construct($data = NULL) {
        \Carrier\Rocket\Rocket::initOnce();
        parent::__construct($data);
    }

    /**
     * 名称
     *
     * Generated from protobuf field <code>string to_name = 1;</code>
     * @return string
     */
    public function getToName()
    {
        return $this->to_name;
    }

    /**
     * 名称
     *
     * Generated from protobuf field <code>string to_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setToName($var)
    {
        GPBUtil::checkString($var, True);
        $this->to_name = $var;

        return $this;
    }

    /**
     * 电话
     *
     * Generated from protobuf field <code>string to_phone = 2;</code>
     * @return string
     */
    public function getToPhone()
    {
        return $this->to_phone;
    }

    /**
     * 电话
     *
     * Generated from protobuf field <code>string to_phone = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setToPhone($var)
    {
        GPBUtil::checkString($var, True);
        $this->to_phone = $var;

        return $this;
    }

    /**
     * 地址
     *
     * Generated from protobuf field <code>string to_addr1 = 3;</code>
     * @return string
     */
    public function getToAddr1()
    {
        return $this->to_addr1;
    }

    /**
     * 地址
     *
     * Generated from protobuf field <code>string to_addr1 = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setToAddr1($var)
    {
        GPBUtil::checkString($var, True);
        $this->to_addr1 = $var;

        return $this;
    }

    /**
     * 城市
     *
     * Generated from protobuf field <code>string to_city = 4;</code>
     * @return string
     */
    public function getToCity()
    {
        return $this->to_city;
    }

    /**
     * 城市
     *
     * Generated from protobuf field <code>string to_city = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setToCity($var)
    {
        GPBUtil::checkString($var, True);
        $this->to_city = $var;

        return $this;
    }

    /**
     * 州
     *
     * Generated from protobuf field <code>string to_state = 5;</code>
     * @return string
     */
    public function getToState()
    {
        return $this->to_state;
    }

    /**
     * 州
     *
     * Generated from protobuf field <code>string to_state = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setToState($var)
    {
        GPBUtil::checkString($var, True);
        $this->to_state = $var;

        return $this;
    }

    /**
     * 国家
     *
     * Generated from protobuf field <code>string to_country = 6;</code>
     * @return string
     */
    public function getToCountry()
    {
        return $this->to_country;
    }

    /**
     * 国家
     *
     * Generated from protobuf field <code>string to_country = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setToCountry($var)
    {
        GPBUtil::checkString($var, True);
        $this->to_country = $var;

        return $this;
    }

    /**
     * 邮编
     *
     * Generated from protobuf field <code>string to_code = 7;</code>
     * @return string
     */
    public function getToCode()
    {
        return $this->to_code;
    }

    /**
     * 邮编
     *
     * Generated from protobuf field <code>string to_code = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setToCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->to_code = $var;

        return $this;
    }

}

