<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rocket.proto

namespace Carrier\Rocket;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 物流跟踪参数
 *
 * Generated from protobuf message <code>rocket.TrackParams</code>
 */
class TrackParams extends \Google\Protobuf\Internal\Message
{
    /**
     * 账号密码
     *
     * Generated from protobuf field <code>.rocket.Auth auth = 1;</code>
     */
    protected $auth = null;
    /**
     * Generated from protobuf field <code>string tracking_number = 2;</code>
     */
    protected $tracking_number = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Carrier\Rocket\Auth $auth
     *           账号密码
     *     @type string $tracking_number
     * }
     */
    public function __construct($data = NULL) {
        \Carrier\Rocket\Rocket::initOnce();
        parent::__construct($data);
    }

    /**
     * 账号密码
     *
     * Generated from protobuf field <code>.rocket.Auth auth = 1;</code>
     * @return \Carrier\Rocket\Auth|null
     */
    public function getAuth()
    {
        return $this->auth;
    }

    public function hasAuth()
    {
        return isset($this->auth);
    }

    public function clearAuth()
    {
        unset($this->auth);
    }

    /**
     * 账号密码
     *
     * Generated from protobuf field <code>.rocket.Auth auth = 1;</code>
     * @param \Carrier\Rocket\Auth $var
     * @return $this
     */
    public function setAuth($var)
    {
        GPBUtil::checkMessage($var, \Carrier\Rocket\Auth::class);
        $this->auth = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string tracking_number = 2;</code>
     * @return string
     */
    public function getTrackingNumber()
    {
        return $this->tracking_number;
    }

    /**
     * Generated from protobuf field <code>string tracking_number = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTrackingNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->tracking_number = $var;

        return $this;
    }

}

